Blog post by Yeonju
ridi/ridicorp.github.io pull request #31
Opened 2017-05-18 05:43 UTC by jaeminbae

연주님 블로그 글 준비가 완료되었습니다. 한 번 검토해주시면 감사하겠습니다.

2017-05-24 12:16 UTC, namenu approved these changes

2017-05-24 12:16 UTC, namenu requested changes
메신져로 코멘트 드렸습니다!

2017-06-27 12:17 UTC, jaeminbae commented
@namenu 글 수정하여 다시 pull request 드립니다. 검토 부탁드려요~!

2017-06-27 16:34 UTC, namenu approved these changes
글이 많이 매끄러워졌네요! :+1:

2017-06-28 02:59 UTC, merged