Blog post - code review
ridi/ridicorp.github.io pull request #36
Opened 2017-06-27 03:42 UTC by kgwangrae

검토 부탁드립니다!

2017-06-27 05:39 UTC, devgrapher requested changes

2017-06-27 05:39 UTC, Devgrapher commented on _posts/blog/2017-06-26-code-review.md
> +> 변경 사항(diff)를 불러오는 속도가 빠르다.
`>` 태그 대신 다른 태그를 사용하는게 좋을거 같아요. 글의 형식이 먼저 개요를 설명하고 그 개요와 관련된 항목 **여러개를 나열하는** 형태인것 같은데 `>`만으로는 앞으로 여러개를 나열할 것임을 예상할 수 없어 글을 읽는데 혼란스러웠습니다. Number나 Bullet list를 써보거나 bold 형태를 고려해볼 수 있을것 같습니다.
또는 개요에서 앞으로 여러개의 항목을 나열할 것임을 분명하게 말하는 것도 방법일것 같습니다.

2017-06-27 05:39 UTC, Devgrapher commented on _posts/blog/2017-06-26-code-review.md
> +> Task에 대한 이해도를 높일 수 있다.
여기도 마찬가지입니다.

2017-06-27 05:39 UTC, Devgrapher commented on _posts/blog/2017-06-26-code-review.md
> +직접 사용해보면서 변경 사항을 확인하는 과정에서 여러 가지 버그를 발견하는 때가 있었습니다. 버그가 있는 경우 수정을 위해서 상당히 많은 코드 변경이 발생할 우려가 있는데, 본격적으로 코드를 검토하기 전에 이러한 버그를 미리 수정할 기회를 가짐으로써 버그 수정을 위한 변경 사항으로 인해 리뷰한 부분을 또다시 리뷰해야하는 일을 줄일 수 있었습니다.
문장이 조금 복잡한거 같은데 다시 간결히 써보면 어떨까요?

2017-06-27 05:39 UTC, Devgrapher commented on _posts/blog/2017-06-26-code-review.md
> +- 리뷰어의 입장에서는, 어떤 표현을 하기 전에 항상 *'작성자가 나름의 최선을 다해서 작성한 코드를 비평하고 있다'*는 점을 유념하면 좋을 것 같았습니다. 특히 작성자가 해당 플랫폼을 처음 다뤄보거나, 프로젝트에 참여한 지 얼마 지나지 않았거나 해서 코드에 대한 이해도가 높기 어려운 상황이라면 더욱 그렇습니다.
![2017-06-27 2 33 34](https://user-images.githubusercontent.com/392804/27572249-b037def0-5b45-11e7-9f26-f449db7c7d0f.png)
회사홈페이지에서 `-`태그의 디자인이 조금 어색하게 나오네요.

2017-06-27 06:05 UTC, imkitae commented on _posts/blog/2017-06-26-code-review.md
> +
이부분 내용이 잘 와닿지가 않네요. 구체적인 경험을 하나만 예로 들어주시면 좋을 것 같습니다.

2017-06-27 06:11 UTC, namenu requested changes

2017-06-27 06:11 UTC, namenu commented on _posts/blog/2017-06-26-code-review.md
> +git을 사용하면서 [GitHub Flow](https://guides.github.com/introduction/flow) 등의 전략에 따라 branch를 적절히 관리한다면 어떤 방법으로든 코드 리뷰를 원활하게 진행할 수 있는 토대가 갖추어진 셈이라고 생각합니다.
git -> Git

2017-06-27 06:11 UTC, namenu commented on _posts/blog/2017-06-26-code-review.md
> +> 변경 사항(diff)를 불러오는 속도가 빠르다.
Quotation 보다는 numbering 으로 표현하는 것이 좋을 듯 합니다.

2017-06-27 06:11 UTC, namenu commented on _posts/blog/2017-06-26-code-review.md
> +이와 더불어 좋은 도구를 사용하면 더 편리하게 리뷰를 진행할 수 있었는데요, 아래와 같은 특징을 가지고 있는 도구가 편리하게 느껴졌던 것 같습니다.
느껴졌던 것 같습니다 -> 편리했습니다, 라는 표현은 어떨까요?

전반적으로 '같습니다' 표현이 많은데 조금 자신있는 문체로 바꾸어도 좋을 뜻 합니다.

2017-06-27 06:11 UTC, namenu commented on _posts/blog/2017-06-26-code-review.md
> +글로만 리뷰 내용을 전달하기에는 어느 정도 한계가 있고, 그렇다고 구두로만 이야기하면 history가 남지 않는 문제가 있습니다. 파일을 쉽게 첨부할 수 있는 도구를 사용하면 screenshot을 이용하는 등의 방법을 통해 리뷰 시의 소통을 더 편리하게 진행할 수 있었던 것 같습니다.
screenshot -> 스크린샷 or 화면캡쳐

2017-06-27 06:11 UTC, namenu commented on _posts/blog/2017-06-26-code-review.md
> +> Task에 대한 이해도를 높일 수 있다.
역시 Quote 보다는 Heading으로

2017-06-27 06:11 UTC, namenu commented on _posts/blog/2017-06-26-code-review.md
> +## 리뷰의 순서 조정하기
아래 문단 내용에 제목이 잘 와닿지 않았습니다.

조정이라함은 순서를 이리저리 재배열 하는 느낌인데,
실제 내용은 관점을 거시적->미시적으로 전환하는 것이라서 그런 듯 해요.

2017-06-27 06:11 UTC, namenu commented on _posts/blog/2017-06-26-code-review.md
> +- 리뷰어의 입장에서는, 어떤 표현을 하기 전에 항상 *'작성자가 나름의 최선을 다해서 작성한 코드를 비평하고 있다'*는 점을 유념하면 좋을 것 같았습니다. 특히 작성자가 해당 플랫폼을 처음 다뤄보거나, 프로젝트에 참여한 지 얼마 지나지 않았거나 해서 코드에 대한 이해도가 높기 어려운 상황이라면 더욱 그렇습니다.
실제 Jekyll 로 띄워보니, 불릿의 baseline 이 맞지 않네요.
이 부분은 @jaeminbae 님께 확인 요청드리겠습니다.

2017-06-27 06:21 UTC, imkitae commented on _posts/blog/2017-06-26-code-review.md
> +> 변경 사항(diff)를 불러오는 속도가 빠르다.
>는 흐리게 처리되어있어 명시성도 좀 떨어지는 것 같네요. 다른 태그로 강조할 필요가 있어보입니다. (H3, Bold 등)

2017-06-27 06:26 UTC, jaeminbae commented on _posts/blog/2017-06-26-code-review.md
> +- 리뷰어의 입장에서는, 어떤 표현을 하기 전에 항상 *'작성자가 나름의 최선을 다해서 작성한 코드를 비평하고 있다'*는 점을 유념하면 좋을 것 같았습니다. 특히 작성자가 해당 플랫폼을 처음 다뤄보거나, 프로젝트에 참여한 지 얼마 지나지 않았거나 해서 코드에 대한 이해도가 높기 어려운 상황이라면 더욱 그렇습니다.
각 항목 사이의 줄바꿈이 p태그로 바뀌면서 p에 먹혀있는 여백이 들어갔습니다. 줄바꿈을 없애면 해결되지만 읽기가 어려우니 아래 이미지와 같이 바꾸는게 어떨까요? (불릿 제거, 앞머리 볼드)
http://imgur.com/a/IeeyG

2017-06-27 08:18 UTC, freekering requested changes
branch, comment, task, commit, history, issue 등 중간 중간 반복되는 영어 용어들은 가독성을 해치는 경향이 있습니다. 전반적으로 그 의미가 통용 가능한 이러한 용어들은 한글 외래어 표기를 사용해도 무방하다고 생각됩니다.

2017-07-05 07:04 UTC, kgwangrae commented on _posts/blog/2017-06-26-code-review.md
> +> 변경 사항(diff)를 불러오는 속도가 빠르다.
numbering으로 하는 경우 indent가 예쁘지 않게 되어서 H3로 했습니다!

2017-07-05 07:27 UTC, namenu approved these changes

2017-07-05 07:27 UTC, namenu commented
가독성이 훨씬 좋아졌네요! :+1:

2017-07-06 08:03 UTC, merged