Ridibooks Frontend stack post 추가
ridi/ridicorp.github.io pull request #41
Opened 2017-08-25 10:58 UTC by nnyamm

리디북스 서점의 frontend stack 을 소개하는 내용 입니다.
잘못된 내용이나 개선되면 좋을 부분들에 대한 의견 부탁드립니다.
감사합니다.

2017-08-30 06:36 UTC, namenu commented
전반적을 영어가 많이 사용되어 있는데 모두 한글로 대체되어야 합니다.
굳이 필요하다면 괄호로 병기를 고려하되 이것도 가독성을 해치기 때문에 최소화할 필요가 있겠습니다.

예)
Frontend -> 프론트엔드
Browser Support -> 브라우저 지원
page -> 페이지

2017-08-30 07:26 UTC, namenu requested changes
국소적으로 리뷰하기는 했습니다만 글의 퀄리티가 조금 아쉽습니다.

요새는 이런류의 글이 많이 등장하고 있어서, 내부적인 고민이 드러나지 않으면 읽고싶은 글이 될 수 없습니다.

다른 회사나 개인의 포스팅을 많이 참고하여 구성을 좋겠습니다.
(백엔드 포스팅은 참고하시면 안됩니다. 당시와는 상황이 많이 다릅니다 😉)

2017-08-30 07:26 UTC, namenu commented on _posts/2017-08-24-ridibooks-frontend-stack.md
> +> IE9 이상, iOS 7 이상, Android kitkat 이상
kitkat -> 4.4 인데 이거 맞나요? ㅋㅋ

2017-08-30 07:26 UTC, namenu commented on _posts/2017-08-24-ridibooks-frontend-stack.md
> +> GA Session 기준 2% 이하는 팀내 논의 후 공식지원 제외
1. GA Session 기준 -> 전체 사용자 중 2% 미만

2. 오해의 소지가 있어서 부연 설명을 하거나, 아예 제거하는 편이 나을 것 같습니다.
지원을 중단하는 이유는 물론 나머지 98%에게 더 집중하기 위해서지만,
포기하는 근거를 다른 사례를 참고하여 보강할 필요가 있겠습니다.

2017-08-30 07:26 UTC, namenu commented on _posts/2017-08-24-ridibooks-frontend-stack.md
> +(참고 : Mobile 기기와 Desktop의 비율이 약 8:2로 모든 프로젝트는 Mobile Browser 우선으로 진행하고 있습니다)
mobile first는 너무 당연해졌고, 8:2가 정확한 수치가 아니므로 제거하는 편이 좋다고 생각합니다.
(밑에도 Desktop 보다 Mobile/Tablet을 먼저 나열하는 것이 좋겠고요.)

2017-08-30 07:26 UTC, namenu commented on _posts/2017-08-24-ridibooks-frontend-stack.md
> +전자책 서점이라는 특성상 **웹 접근성과 웹 표준을 지키기 위해 더욱 노력**하고 있습니다.
어떻게(?) 라는 궁금증을 강하게 남기기 때문에 부연설명을 추가하거나 빼주세요.

2017-08-30 07:26 UTC, namenu commented on _posts/2017-08-24-ridibooks-frontend-stack.md
> +HTML은 **HTML5**를 사용하며 초기 HTML5 미지원 Browser들은(IE8 이하) [HTML5 Shiv](https://github.com/aFarkas/html5shiv) 로 polyfill 하여 대응 하고 있습니다.
위에서는 IE11을 지원하고, 초기에도 IE9을 지원한다고 되어있는데 여기엔 IE8이 등장합니다.

2017-08-30 07:26 UTC, namenu commented on _posts/2017-08-24-ridibooks-frontend-stack.md
> +CSS는 **CSS3**를 사용하며 초기에는 외주업체에 의해 Vanilla CSS로 확장 불가능한 구조로 개발되어 있었기 때문에 [Less](http://lesscss.org/) 를 도입하여 각 page 단위로 모든 CSS를 refactoring 하였습니다.
너무 예전 기록까지 언급할 필요는 없겠습니다.
(그닥 궁금해하거나 매력적이지 않은 내용이기도 하고요)

2017-08-30 07:26 UTC, namenu commented on _posts/2017-08-24-ridibooks-frontend-stack.md
> +하지만 도입 초기 적절한 Vendor prefix plugin 없이  Less의 mixin 으로 대응하였고, Lint tool 없이 몇가지 자체규칙을 정의한 문서를 통해 convention 을 적용하였기 때문에 점차 기술부채가 늘고 있습니다.
"less mixin, 자체규칙 -> 기술부채를 늘어남"
이 부분의 논리적인 연결이 부자연스럽습니다. 없어도 되는 부분입니다.

2017-08-30 07:26 UTC, namenu commented on _posts/2017-08-24-ridibooks-frontend-stack.md
> +## JS
JS -> JavaScript

2017-08-30 07:26 UTC, namenu commented on _posts/2017-08-24-ridibooks-frontend-stack.md
> +초기 jQuery 기반으로 간단한 유효성검사 및 UI조작 등의 소극적인 역할을 담당하다 보니 관리주체 없이 컨벤션 없는 코드가 축적되어 왔습니다.
어렴풋이 어떤 의미인지는 짐작할 수 있으나, 외부인이라면 이해하기가 어려워 보입니다.
또한 소극적인 역할을 하는것과 관리주체가 없는 것에는 연관성이 없습니다.

2017-08-30 07:26 UTC, namenu commented on _posts/2017-08-24-ridibooks-frontend-stack.md
> +ES5 및 RequireJS를 도입하고 Package 관리 tool(npm, Bower)을 도입 하였지만 이후 Frontend 개발환경이 빠른속도로 발전하였고 JS의 역할이 다양해 짐에 따라 이에 대응하기 위해 최신 spec의 JS 및 lint tool 그리고 JS Framework를 도입하기로 결정했습니다.
문장 호흡이 길어서 한 번 끊었으면 좋겠습니다.

2017-08-30 07:26 UTC, namenu commented on _posts/2017-08-24-ridibooks-frontend-stack.md
> +  이미 Backend part 에서 운영중에 있고 Vue.js를 지원하기 때문에 선택
갑자기 반말이 ㅎㅎ;;

2017-08-30 07:26 UTC, namenu commented on _posts/2017-08-24-ridibooks-frontend-stack.md
> +### Package Manager
패키지 매니저 관련 내용은 굳이 필요가 없습니다.

2017-08-30 07:26 UTC, namenu commented on _posts/2017-08-24-ridibooks-frontend-stack.md
> +## RSG
RSG 관련된 내용은 흐름이 어색하고, 내용적으로도 특별함이 없습니다.
통으로 제거하고.. 기회가 된다면 다른 글에서 제대로 다루면 좋겠습니다.

2017-08-30 07:26 UTC, namenu commented on _posts/2017-08-24-ridibooks-frontend-stack.md
> +## RSG
그보다 클로징 멘트가 필요해 보입니다.
예)
 - 앞으로의 방향
 - 그 방향으로 나아가기 위한 우리만의 원칙

2017-10-16 03:35 UTC, nnyamm commented
@namenu
회고 해보니 내용적으로 아쉬운 부분들이 많더라고요
 - 전체적인 문장 완성도
 - 글의 컨셉 (대상이 명확하지 않음)
 - 내용의 깊이 (단순 정보 나열)
제안주신 개선사항들을 적용하여 불필요한 내용들은 덜어내어 
[사내 블로그](https://ridicorp.atlassian.net/wiki/spaces/DevSpace/blog/2017/10/13/199131309 )에 1차적으로 공유 하였고 위의 미진한 부분들을 보완해서 추후 다시 요청드릴께요!

2017-10-16 03:39 UTC, closed without merging

2017-10-16 05:22 UTC, namenu commented
@nnyamm 네, 업그레이드 된 버전 기대하겠습니다 ㅎㅎ