Post/ridistory front dev
ridi/ridicorp.github.io pull request #45
Opened 2017-09-13 05:51 UTC by antiline

2017-09-13 10:00 UTC, freekering requested changes

2017-09-13 10:00 UTC, freekering commented on _posts/2017-09-13-how-to-develop-ridistory-front.md
> +아, 시간! 콘텐츠를 유통하는 플랫폼을 만드는 입장에서 초기 시장을 선점하는 일은 굉장히 중요합니다. 사용자 입장에서는 이미 익숙한 UX를 경험하고 있는 서비스를 통해서 양질의 콘텐츠가 지속해서 공급된다면 구태여 모험을 하면서까지 다른 서비스를 사용할 이유가 없습니다. 신규 서비스 입장에서 빠르게 서비스를 완성하여 다른 서비스보다 먼저 시장에 진입하는 것
`UX`의 `X`와 뒤의 `경험` 이 동어 반복인 느낌이 있습니다. `이미 익숙한 UX를 제공하고 있는 서비스` 가 좀 더 자연스럽게 느껴집니다.

2017-09-13 10:00 UTC, freekering commented on _posts/2017-09-13-how-to-develop-ridistory-front.md
> +오래된 기억 상자 속에서 몬타나 존스라는 만화영화 이야기를 꺼내온 이유는 신규 서비스를 개발하는 입장에서 니트로 박사에게 어쩐지 묘한 공감했기 때문입니다. 스타트업에서 개발을 하는 많은 개발자분들도 함께 공감할 수 있는 이야기라는 생각이 듭니다.
`묘한` -> `묘하게`

2017-09-13 10:00 UTC, freekering commented on _posts/2017-09-13-how-to-develop-ridistory-front.md
> +그래서 웹앱이었습니다. 서비스 론칭까지 앞으로 4개월, 선택지는 그리 많지 않았습니다. 사실 개발 초기에는 서버 개발자 2명밖에 없었습니다. 팀 내에 네이티브 앱 개발 경험을 가진 개발자가 있더라도 빠른 서비스 론칭을 위해서는 결국 웹앱 쪽으로 방향을 잡을 수밖에 없었습니다. 동일한 서비스를 구현하는 코드를 Android, iOS 각각의 플랫폼별로 두 벌
`서비스 론칭까지 앞으로 4개월`. 현재 시점에서 서술하고 있으므로 `앞으로`는 빼는게 자연스러운 것 같습니다.

2017-09-13 10:00 UTC, freekering commented on _posts/2017-09-13-how-to-develop-ridistory-front.md
> +웹앱으로의 방향이 정해지고부터 리디스토리 개발팀은 익숙하고 빠르게 결과물을 낼 수 있는 방식으로 작업을 하기 시작했습니다. 서비스에 필요한 UI를 HTML로 구성하고 그 안에서 동적으로 변경되는 부분들은 `django`에서 지원하는 `jinja2`라는 템플릿을 통해서 구성하는 전통적인(?) 방식이었습니다. 그렇게 서비스의 얼개가 대강 잡혔을 때쯤 우리는
`django`, `jinja2` 같은 것들에는 링크도 함께 있으면 좋을 것 같습니다. (최초 등장시 한번만)

2017-09-13 10:00 UTC, freekering commented on _posts/2017-09-13-how-to-develop-ridistory-front.md
> +앞서 언급한 사용자 정보에 대한 데이터 외에도 여러 화면에서 공통으로 사용되는 데이터는 또 있었습니다. 바로 작품에 대한 메타 데이터였습니다. 작품의 pk와 제목, 저자 정보 등으로 구성된 이 데이터는 여러 화면에서 공통으로 사용되고 있었고 매화면 이동 시마다 중복해서 서버에서 내려주고 있었습니다. 아래와 같은 시나리오로 예를 들 수 있을 것 같습니다.
`메타 데이터` 는 영어로 한단어 `metadata` 이므로 붙여쓰는게 좋겠습니다. 또 처음부터 `pk`라고 표현하기보다는 `Primary Key(이하 pk)` 같은 식으로 한번 정도 명시해주는게 좋을 것 같습니다.

2017-09-13 10:00 UTC, freekering commented on _posts/2017-09-13-how-to-develop-ridistory-front.md
> +클라이언트 사이드에서 데이터가 중복으로 저장되어 메모리 사용량이 늘어나는 것은 차치하더라도 전송 시마다 트래픽을 과하게 차지하면서 화면 로딩을 늦추는 것을 저희 개발팀은 용서할 수 없었습니다.
`차지` 보다는 `소모` 나 `소비` 가 어울릴 것 같습니다.

2017-09-13 10:00 UTC, freekering commented on _posts/2017-09-13-how-to-develop-ridistory-front.md
> +그저 어서 리디스토리가 성장해서 팀의 구조가 커졌으면 하는 개인적인 바람을 적으면서 글을 마칩니다.
결론이 좀 특이한 방향이긴 한데...  팀의 규모면 몰라도 구조가 커지는건 이상하므로 `팀의 규모가 커져서 이것 저것 시도해볼 수 있으면 좋겠다` 정도로 정리하는건 어떨까요?

2017-09-13 12:33 UTC, genesos requested changes

2017-09-13 12:33 UTC, genesos commented on _posts/2017-09-13-how-to-develop-ridistory-front.md
> +## Entity의 등장
React 는 개념과 흐름만 간단히 알고있어서 잘 모르겠는데,
1. Entity는 일반 프로그래밍에서 쓰는 개념인가요? (혹은 DDD에 있는?)
2. React 요소중의 Entity 를 명칭하는건가요?
3. React 특정 구현을 말하는건가요? (https://www.npmjs.com/package/react-entity 이런거?)

2017-09-13 12:33 UTC, genesos commented on _posts/2017-09-13-how-to-develop-ridistory-front.md
> +![Entity 설명 이미지](/blog/img/2017-09-13/entity.png){: data-action="zoom" }
"Client", "Store" 라는게 어느 영역에서 관리되고 있는 항목인가요?
JS? React? HTML? 안드로이드? OS?
도표만 보았을때 "브라우저 Cache" 를 이용했다고도 이해 할 수 있는 내용인것 같습니다~

2017-09-13 12:33 UTC, genesos commented on _posts/2017-09-13-how-to-develop-ridistory-front.md
> +![Entity 설명 이미지](/blog/img/2017-09-13/entity.png){: data-action="zoom" }
혹 여러 영역들 중에서도 특정영역이 선택되었다는 검토과정이 있다면 추가되어도 좋을것 같습니다.

2017-09-13 12:33 UTC, genesos commented on _posts/2017-09-13-how-to-develop-ridistory-front.md
> +개발팀은 하던 일을 모두 중지하고 회의실에 모여 머리를 맞대고 대책을 강구하기 시작합니다. 길고 긴 회의 끝에 기존의 방법을 버리고 SPA로의 전면 개편이라는 선택지로 겁도 없이 손을 뻗었습니다. SPA 개발을 도와줄 도구로써 `react`와 `angular`를 비교했고, 학습곡선이 낮고 좀 더 자유로운 방식으로 사용 가능한 `react`에 `react-
SPA면 `Single Page Application` 맞죠? 최초 한번 정도 괄호로 설명부탁드립니다.

2017-09-13 12:33 UTC, genesos commented on _posts/2017-09-13-how-to-develop-ridistory-front.md
> +네, 사실 `react` 도입 단계에서 `redux`의 도입까지 고려했으나 당시 필요 이상의 오버 엔지니어링이라는 판단이 들어 배제했었고 나중에야 그것이 잘못된 판단이라는 것을 깨달았습니다. 클라이언트 사이드에서 상태를 유지하는 문제, 컴포넌트 depth를 따라서 데이터를 내려줘야 하는 문제 모두 `redux`를 도입함으로써 깔끔하게 해결할 수 있는 문제
"Redux를 도입함으로써 해결할 수 있는 문제였습니다. 더불어 XXX 를 도입하면서 XXX를 할 수 있었습니다"
아래 3가지 중에 어떤건가요?

1. "Redux를 도입을 했어야했는데 못했다. 그 대신 redux-thunk, reselect 을 사용해서 해결했다"
2. "Redux를 도입을 했어야했는데 못했다. 도입했다면 redux-thunk, reselect와 redux도 같이 사용 할 수 있었을텐데.."
3. "잠깐 후회했지만 빠르게 redux를 다시 도입했고, 뿐만아니라 redux-thunk, reselect 도 도입했다"

2017-09-14 03:40 UTC, iamchanu requested changes

2017-09-14 03:40 UTC, iamchanu commented on _posts/2017-09-13-how-to-develop-ridistory-front.md
> +몬타나 존스 라는 만화영화가 있었습니다. 1990년대 중반쯤에 방영되었던 것으로 기억이 나네요. 에피소드마다 의인화된 사자와 호랑이들 유물 유적을 탐험하다 제로경으로 대표되는 악의 무리와 부딪힙니다. 제로경은 니트로 박사라는 부하가 만들어준 로봇을 타고 주인공의 앞길을 막고, 쫓고 쫓기는 아슬아슬한 활극 끝에 결국 정의의 편인 주인공이 승리하곤 합니다.
...사자와 호랑이들*이* 유적을 탐험하다...

2017-09-14 03:40 UTC, iamchanu commented on _posts/2017-09-13-how-to-develop-ridistory-front.md
> +아, 시간! 콘텐츠를 유통하는 플랫폼을 만드는 입장에서 초기 시장을 선점하는 일은 굉장히 중요합니다. 사용자 입장에서는 이미 익숙한 UX를 제공하고 있는 서비스 통해서 양질의 콘텐츠가 지속해서 공급된다면 구태여 모험을 하면서까지 다른 서비스를 사용할 이유가 없습니다. 신규 서비스 입장에서 빠르게 서비스를 완성하여 다른 서비스보다 먼저 시장에 진입하는 것이
UX를 제공하고 있는 서비스*를* 통해서

2017-09-14 03:40 UTC, iamchanu commented on _posts/2017-09-13-how-to-develop-ridistory-front.md
> +아, 시간! 콘텐츠를 유통하는 플랫폼을 만드는 입장에서 초기 시장을 선점하는 일은 굉장히 중요합니다. 사용자 입장에서는 이미 익숙한 UX를 제공하고 있는 서비스 통해서 양질의 콘텐츠가 지속해서 공급된다면 구태여 모험을 하면서까지 다른 서비스를 사용할 이유가 없습니다. 신규 서비스 입장에서 빠르게 서비스를 완성하여 다른 서비스보다 먼저 시장에 진입하는 것이
> 신규 서비스 입장에서 빠르게 서비스를 완성하여 다른 서비스보다 먼저 시장에 진입하는 것이 무엇보다 중요하지만 리디스토리는 조건이 좋지 못했습니다.

문장이 어딘가모르게 어색한데요... `입장` 이라는 표현이 약간 안어울리는 듯 해 보입니다.
그리고 `서비스`라는 단어가 너무 많이 들어갔는데요, `신규 서비스`와 `다른 서비스`라는 표현에 쓰인 *서비스*와 `서비스를 완성`에 쓰인 *서비스*는 의미가 살짝 다른 듯 합니다. 후자를 `제품`으로 바꿔보겠습니다. (이것도 좀 마땅찮은데 다른 대안이 떠오르지 않아서...)

> 신규 서비스에게는 빠르게 제품을 완성하여 다른 서비스보다 먼저 시장에 진입하는 것이 무엇보다 중요합니다. 하지만 리디스토리는 조건이 좋지 못했습니다.

2017-09-14 03:40 UTC, iamchanu commented on _posts/2017-09-13-how-to-develop-ridistory-front.md
> +웹앱으로의 방향이 정해지고부터 리디스토리 개발팀은 익숙하고 빠르게 결과물을 낼 수 있는 방식으로 작업을 하기 시작했습니다. 서비스에 필요한 UI를 HTML로 구성하고 그 안에서 동적으로 변경되는 부분들은 [django](https://www.djangoproject.com/)에서 지원하는 [jinja2](http://jinja.pocoo.org/)라는 템
`웹앱으로의 방향이 정해지고부터` -> `방향이 웹앱으로 정해지고 나서부터`

2017-09-14 03:40 UTC, iamchanu commented on _posts/2017-09-13-how-to-develop-ridistory-front.md
> +개발팀 내부에서 사용하는 Jira의 태스크 보드에는 서비스 화면의 이름이 쓰인 태스크들이 무더기로 등장했습니다. 개발자들은 그 태스크 들을 하나씩 가져와 기존에 jinja2 템플릿으로 되어 있는 화면을 `react` 기반으로 옮기기 시작했습니다. 단순 포팅을 넘어서서 화면의 각 구성요소를 적절하게 컴포넌트화하여 재사용성을 높이고 각 화면들의 시나리오들을
`태스크 보드에는` -> `태스크보드에는`
`그 태스크 들을` -> `그 태스크들을`

2017-09-14 03:40 UTC, iamchanu commented on _posts/2017-09-13-how-to-develop-ridistory-front.md
> +이 문제를 해결하기 위해서 저희는 클라이언트 사이드에서 상태와 데이터를 저장하고 관리하는 코드들을 추가하기 시작했습니다. 서버로부터 받아온 댓글 목록 데이터는 이곳에 저장되고 사용자가 새로운 댓글을 작성하면 서버로 전송됨과 동시에 클라이언트 사이드 저장소에도 추가되게 됩니다. 이제 댓글 목록 화면으로 돌아오더라도 이 저장소에 있는 데이터를 기반으로 화면을
`사이드` -> `측` 또는 `쪽`?

2017-09-14 03:40 UTC, iamchanu commented on _posts/2017-09-13-how-to-develop-ridistory-front.md
> +네, 사실 `react` 도입 단계에서 `redux`의 도입까지 고려했으나 당시 필요 이상의 오버 엔지니어링이라는 판단이 들어 배제했었고 나중에야 그것이 잘못된 판단이라는 것을 깨달았습니다. 클라이언트 사이드에서 상태를 유지하는 문제, 컴포넌트 depth를 따라서 데이터를 내려줘야 하는 문제 모두 `redux`를 도입함으로써 깔끔하게 해결할 수 있는 문제
여기까지만 읽으면 redux 를 도입하지 않은 것으로 여겨집니다.
그런데 아래 결론부에 결국 redux 를 도입한 것 같은 언급이 나와서 헷갈립니다.

2017-09-14 07:03 UTC, antiline commented on _posts/2017-09-13-how-to-develop-ridistory-front.md
> +## Entity의 등장
Entity 는 그냥 저희가 내부적으로 만든 개념입니다.

2017-09-14 07:21 UTC, freekering requested changes

2017-09-14 07:21 UTC, freekering commented on _posts/2017-09-13-how-to-develop-ridistory-front.md
> +네, 너무 느렸습니다. 느릴 수밖에 없었습니다. 스마트폰에 앱이라는 형태로 인스톨된 이상 사용자는 여타 다른 네이티브 애플리케이션과 비슷한 반응성을 기대하며 리디스토리 앱을 이용하게 됩니다. 하지만 리디스토리 앱의 내부는 웹과 동일한 형태로 구현이 되었으니 사용자 입장에서는 어딘가 모르게 굼뜨다는 인상을 받게 됩니다. 매화면 이동 시마다 흰 화면이 순간적
(가능하다면) 얼마나 느린지 실제로 확인할 수 있는 당시의 동작 화면 동영상 같은게 있으면 좋을 것 같습니다.
뒤에서 SPA로 바뀐 지금과 비교할 수 있으면 더 좋을 거 같고요. 자료가 남아 있지 않으면 할 수 없고..

2017-09-14 07:21 UTC, freekering commented on _posts/2017-09-13-how-to-develop-ridistory-front.md
> +description: "웹앱을 네이트브앱처럼 보이게 하기"
`네이트브` -> `네이티브`

2017-09-14 07:21 UTC, freekering commented on _posts/2017-09-13-how-to-develop-ridistory-front.md
> +몬타나 존스 라는 만화영화가 있었습니다. 1990년대 중반쯤에 방영되었던 것으로 기억이 나네요. 에피소드마다 의인화된 사자와 호랑이가 유물 유적을 탐험하다 제로경으로 대표되는 악의 무리와 부딪힙니다. 제로경은 니트로 박사라는 부하가 만들어준 로봇을 타고 주인공의 앞길을 막고, 쫓고 쫓기는 아슬아슬한 활극 끝에 결국 정의의 편인 주인공이 승리하곤 합니다.
`몬타나 존스` 관련 삽화를 곁들이면 더 좋은 도입부가 될 거 같습니다.

2017-09-14 07:25 UTC, antiline commented on _posts/2017-09-13-how-to-develop-ridistory-front.md
> +![Entity 설명 이미지](/blog/img/2017-09-13/entity.png){: data-action="zoom" }
store는 redux 의 저장소 개념 단어입니다. -> redux에 데이터를 저장한다는 내용입니다.
http://redux.js.org/docs/api/Store.html

2017-09-14 07:31 UTC, genesos commented on _posts/2017-09-13-how-to-develop-ridistory-front.md
> +![Entity 설명 이미지](/blog/img/2017-09-13/entity.png){: data-action="zoom" }
그러면 도표에는 "Client"나 "Store" 보다 "React"(혹은 "JS")-"Redux" 라고 쓰는게 바로 이해될것 같네요~

2017-09-14 07:33 UTC, genesos commented on _posts/2017-09-13-how-to-develop-ridistory-front.md
> +## Entity의 등장
내부 개념이라면 설명이 필요할것 같습니다~
(예를들어 외부의 어떤개념과 비슷하다거나, 구현은 Redux로 했다거나)

2017-09-14 08:12 UTC, antiline commented on _posts/2017-09-13-how-to-develop-ridistory-front.md
> +네, 사실 `react` 도입 단계에서 `redux`의 도입까지 고려했으나 당시 필요 이상의 오버 엔지니어링이라는 판단이 들어 배제했었고 나중에야 그것이 잘못된 판단이라는 것을 깨달았습니다. 클라이언트 사이드에서 상태를 유지하는 문제, 컴포넌트 depth를 따라서 데이터를 내려줘야 하는 문제 모두 `redux`를 도입함으로써 깔끔하게 해결할 수 있는 문제
관련해서 문장을 추가했습니다.

2017-09-14 08:18 UTC, antiline commented on _posts/2017-09-13-how-to-develop-ridistory-front.md
> +아, 시간! 콘텐츠를 유통하는 플랫폼을 만드는 입장에서 초기 시장을 선점하는 일은 굉장히 중요합니다. 사용자 입장에서는 이미 익숙한 UX를 제공하고 있는 서비스 통해서 양질의 콘텐츠가 지속해서 공급된다면 구태여 모험을 하면서까지 다른 서비스를 사용할 이유가 없습니다. 신규 서비스 입장에서 빠르게 서비스를 완성하여 다른 서비스보다 먼저 시장에 진입하는 것이
관련해서 문장들을 좀 바꿔봤습니다.

2017-09-14 08:19 UTC, antiline commented on _posts/2017-09-13-how-to-develop-ridistory-front.md
> +네, 너무 느렸습니다. 느릴 수밖에 없었습니다. 스마트폰에 앱이라는 형태로 인스톨된 이상 사용자는 여타 다른 네이티브 애플리케이션과 비슷한 반응성을 기대하며 리디스토리 앱을 이용하게 됩니다. 하지만 리디스토리 앱의 내부는 웹과 동일한 형태로 구현이 되었으니 사용자 입장에서는 어딘가 모르게 굼뜨다는 인상을 받게 됩니다. 매화면 이동 시마다 흰 화면이 순간적
ㅠㅠ 그런..자료는 없...

2017-09-14 08:19 UTC, antiline commented on _posts/2017-09-13-how-to-develop-ridistory-front.md
> +몬타나 존스 라는 만화영화가 있었습니다. 1990년대 중반쯤에 방영되었던 것으로 기억이 나네요. 에피소드마다 의인화된 사자와 호랑이가 유물 유적을 탐험하다 제로경으로 대표되는 악의 무리와 부딪힙니다. 제로경은 니트로 박사라는 부하가 만들어준 로봇을 타고 주인공의 앞길을 막고, 쫓고 쫓기는 아슬아슬한 활극 끝에 결국 정의의 편인 주인공이 승리하곤 합니다.
저작권같은거 문제 있을까봐 안했는데 넣어볼께요.

2017-09-14 08:22 UTC, earus requested changes

2017-09-14 08:22 UTC, earus commented on _posts/2017-09-13-how-to-develop-ridistory-front.md
> +방향이 웹앱으로 정해지고 나서부터 리디스토리 개발팀은 익숙하고 빠르게 결과물을 낼 수 있는 방식으로 작업을 하기 시작했습니다. 서비스에 필요한 UI를 HTML로 구성하고 그 안에서 동적으로 변경되는 부분들은 [django](https://www.djangoproject.com/)에서 지원하는 [jinja2](http://jinja.pocoo.org/)라는
링크 걸리는 부분에 공식 명칭의 대소문자를 반영해주는게 좋을 것 같습니다~

- django => Django
- jinja2 => Jinja2

근데 Django 같은 경우 로고는 모두 소문자이고 문서 등엔 D가 대문자여서 좀 애매하네요. 😳

2017-09-14 08:22 UTC, earus commented on _posts/2017-09-13-how-to-develop-ridistory-front.md
> +개발팀은 하던 일을 모두 중지하고 회의실에 모여 머리를 맞대고 대책을 강구하기 시작합니다. 길고 긴 회의 끝에 기존의 방법을 버리고 Single Page Application(이하  SPA)로의 전면 개편이라는 선택지로 겁도 없이 손을 뻗었습니다. SPA 개발을 도와줄 도구로써 `react`와 `angular`를 비교했고, 학습곡선이 낮고 좀 더 자유로운
여기도 공식 명칭의 대소문자가 반영되면 좋을 것 같아요. :)

2017-09-14 08:22 UTC, earus commented on _posts/2017-09-13-how-to-develop-ridistory-front.md
> +개발팀은 네이티브앱 처럼 보이기 위해 많은 노력을 했습니다. 특히 속도 관련해서 많은 시도를 했습니다. 여러 화면에서 데이터를 최신으로 유지하기 위해 `redux`를 도입한다던가, `entity`라는 개념을 만들어 중복 데이터 및 서버 응답의 용량을 줄이는 것도 이런 노력의 일환이었죠. 물론 이것 외에도 필연적으로 느릴 수 밖에 없는 실행속도를 UX를 통
리디스피치 때 말씀하셨던 안드로이드에서의 별도 웹뷰 라이브러리가 적용되었다면 그 내용도 추가되면 좋을 것 같아요.

2017-09-14 08:22 UTC, freekering commented on _posts/2017-09-13-how-to-develop-ridistory-front.md
> +몬타나 존스 라는 만화영화가 있었습니다. 1990년대 중반쯤에 방영되었던 것으로 기억이 나네요. 에피소드마다 의인화된 사자와 호랑이가 유물 유적을 탐험하다 제로경으로 대표되는 악의 무리와 부딪힙니다. 제로경은 니트로 박사라는 부하가 만들어준 로봇을 타고 주인공의 앞길을 막고, 쫓고 쫓기는 아슬아슬한 활극 끝에 결국 정의의 편인 주인공이 승리하곤 합니다.
출처 표기하면 괜찮지 않을까요

2017-09-14 10:51 UTC, antiline commented on _posts/2017-09-13-how-to-develop-ridistory-front.md
> +몬타나 존스 라는 만화영화가 있었습니다. 1990년대 중반쯤에 방영되었던 것으로 기억이 나네요. 에피소드마다 의인화된 사자와 호랑이가 유물 유적을 탐험하다 제로경으로 대표되는 악의 무리와 부딪힙니다. 제로경은 니트로 박사라는 부하가 만들어준 로봇을 타고 주인공의 앞길을 막고, 쫓고 쫓기는 아슬아슬한 활극 끝에 결국 정의의 편인 주인공이 승리하곤 합니다.
이미지를 찾아서 추가 해봤는데.

youtube에서 동영상이 안짤린다면 이 동영상이 더 좋을지도 모르곘네요.
https://www.youtube.com/watch?v=x8rRQHtlaKc

2017-09-15 13:25 UTC, antiline commented
@earus @freekering @genesos @iamchanu @namenu  리뷰 반영 했습니다.

2017-09-17 04:53 UTC, namenu commented
조사, 시제, 띄어쓰기 관련된 문법적인 오류를 수정하였습니다.
그 외 다소 민감한 표현을 수정하였습니다.

2017-09-17 04:54 UTC, namenu approved these changes

2017-09-17 06:39 UTC, freekering approved these changes

2017-09-18 01:27 UTC, namenu commented
@Devgrapher @imkitae 1차 리뷰가 끝나서, 두 분께도 리뷰 요청 드립니다. 
@antiline 리뷰 과정이 많이 길지만, publish 이후에는 고치기 어렵기 때문에 이 점 양해 부탁드립니다.

2017-09-18 02:27 UTC, genesos approved these changes

2017-09-18 02:44 UTC, Devgrapher commented on _posts/2017-09-13-how-to-develop-ridistory-front.md
> +아, 시간! 콘텐츠를 유통하는 플랫폼을 만드는 입장에서 초기 시장을 선점하는 일은 굉장히 중요합니다. 사용자 입장에서는 이미 익숙한 UX를 제공하고 있는 플랫폼을 통해서 양질의 콘텐츠가 지속해서 공급된다면 구태여 모험을 하면서까지 다른 제품을 사용할 이유가 없습니다. 또한 콘텐츠 제공자 입장에서도 신생 플랫폼에 콘텐츠를 제공하는것 보다 시장을 선점한 플랫
혹시.. `콘텐츠 제공자`라는 표현이 너무 우리 입장에서 선택된 단어는 아닐까요? 왠지 읽는 사람 입장에서는 `콘텐츠 제작자`라는 표현이 더 직관적으로 와 닿을것 같다는 생각이 드네요.

2017-09-18 02:44 UTC, Devgrapher commented on _posts/2017-09-13-how-to-develop-ridistory-front.md
> +개발팀은 네이티브앱 처럼 보이기 위해 많은 노력을 했습니다. 특히 속도 관련해서 많은 시도를 했습니다. 여러 화면에서 데이터를 최신으로 유지하기 위해 `Redux`를 도입한다던가, `Entity`라는 개념을 만들어 중복 데이터 및 서버 응답의 용량을 줄이는 것도 이런 노력의 일환이었죠. 저사양 안드로이드 기기들을 위해 커스텀 웹뷰를 어플에 내장하기도 했습
`속도 관련해서`는 너무 구어체인것 같고 `속도와 관련해서` 혹은 `성능 개선 측면에서`가 더 나은것 같습니다.

2017-09-18 07:41 UTC, imkitae requested changes
가독성에 대한 내용만 요청드렸습니다. 내용은 문제없는 것 같습니다. 추가로 speaker deck에 올라간 아연님 발표자료(https://speakerdeck.com/ridi/ridiseutori-seongneung-gaeseon-iyagi) 가 참고하는데 도움이 될 것 같은데 링크를 포함시키면 어떨까요?

2017-09-18 07:41 UTC, imkitae commented on _posts/2017-09-13-how-to-develop-ridistory-front.md
> +아, 시간! 콘텐츠를 유통하는 플랫폼을 만드는 입장에서 초기 시장을 선점하는 일은 굉장히 중요합니다. 사용자 입장에서는 이미 익숙한 UX를 제공하고 있는 플랫폼을 통해서 양질의 콘텐츠가 지속해서 공급된다면 구태여 모험을 하면서까지 다른 제품을 사용할 이유가 없습니다. 또한 콘텐츠 제공자 입장에서도 신생 플랫폼에 콘텐츠를 제공하는것 보다 시장을 선점한 플랫
이 문단이 잘 읽히지 않네요. 비슷한 표현과 조사가 반복되는 부분이 많은 것 같습니다. (~를 ~하는, ~ 입장에서) 문장은 확실히 다듬었으면 좋겠는데 어떤 식으로 다듬어야 할지는 고민이 됩니다.

다음은 제가 나름 수정해본건데 이것도 베스트는 아닌 것 같아요.. 참고만 해주세요.

`아, 시간! 콘텐츠를 유통하는 플랫폼으로서 초기 시장을 선점하는 일은 굉장히 중요합니다. 사용자는 이미 기존 플랫폼이 제공하는 UX에 익숙해져 있습니다. 특별한 이유가 없다면 구태여 다른 제품을 사용하려 하지 않습니다. 또한 콘텐츠 제공자는 시장에 영향력을 가진 플랫폼을 선호하기 때문에, 신생 플랫폼 입장에서 콘텐츠를 확보하려면 많은 노력이 필요합니다`

2017-09-18 07:41 UTC, imkitae commented on _posts/2017-09-13-how-to-develop-ridistory-front.md
> +## 웹앱
다른 부제들은 문단의 내용을 간단하게나마 추측할 수 있게 해주는데 이 `웹앱`만 너무 단순한 것 같습니다. 약간 더 자세한 부제였으면 좋겠어요.

2017-09-18 07:42 UTC, iamchanu approved these changes

2017-09-18 08:37 UTC, devgrapher approved these changes

2017-09-18 14:52 UTC, imkitae approved these changes

2017-09-19 03:04 UTC, earus approved these changes

2017-09-19 03:16 UTC, merged

2017-09-19 03:23 UTC, namenu commented
merge 하여 헤더 이미지 추가했습니다.
author의 gravatar만 수정한 뒤에 `publish: true` 로 master에 커밋해 주시면 되겠습니다.
🎉