Binlog Collector 포스팅
ridi/ridicorp.github.io pull request #46
Opened 2017-09-18 09:54 UTC by kobi97

플랫폼팀에서 MariaDB Binlog 기반으로 이력 데이터를  쌓기 위해서 고민했던 내용입니다.

소스 공개는 블로그 포스팅시 같이 공개하면 좋을 것 같습니다.

감사합니다.

2017-09-22 09:06 UTC, antiline requested changes

2017-09-22 09:06 UTC, antiline commented on _posts/2017-09-18-binlog-collector.md
> +아래 그림은 [Designing Data-Intensive Applications](https://dataintensive.net)의 저자, Martin Kleppmann[1]가 쓴 [Logs for Data Infrastructure](https://martin.kleppmann.com/2015/05/27/logs-for-data-infrastructu
여기는 참고문헌으로 빼면 좋을것 같습니다.

2017-09-22 09:06 UTC, antiline commented on _posts/2017-09-18-binlog-collector.md
> +![그림 1. Logs For Infrastructure](/blog/img/binlog01.png){: data-action="zoom" }
개인적으로는 다른 사람이 그린 그림을 가져와서 쓰는게 좋지 않다고 생각됩니다.

2017-09-22 09:06 UTC, antiline commented on _posts/2017-09-18-binlog-collector.md
> +데이터베이스의 **Change Data Capture(이하 CDC)**는 DB의 변경 이벤트들(Insert/Update/Delete/...)을 **단일 시퀀스 레코드 저장(이하 Append 로그)** 방식의 Binary 로그 파일에 저장하고
처음에 기술 소개가 아니라 이 글이 왜 시작되었는지 목적이 먼저 나오는게 좋을것 같습니다.

2017-09-22 09:06 UTC, antiline commented on _posts/2017-09-18-binlog-collector.md
> +여러 언어**(Java/Python/PHP/Node.js/Go)**로 구현된,
언어 선택 은 빼도 될 것 같습니다.

2017-09-22 09:06 UTC, antiline commented on _posts/2017-09-18-binlog-collector.md
> +CDC 기술을 이용하여 MariaDB의 테이블 변경사항을 추적하는 방법을 찾아보니,
여기 문단은 제거되어도 문맥상 괜찮을것같습니다.

2017-09-22 09:06 UTC, antiline commented on _posts/2017-09-18-binlog-collector.md
> +![그림 4. SHOW BINLOG EVENTS 결과](/blog/img/binlog04.png){: data-action="zoom" }
여백이 많아 3번 내용이 옆으로 간것 같은데 보고 이해하기 어렵습니다.

2017-09-22 09:06 UTC, antiline commented on _posts/2017-09-18-binlog-collector.md
> +실제 Binlog 이벤트들을 처음 보신 분들이 계실 수 있어서, 샘플 쿼리를 실행 한 후 `SHOW BINLOG EVENTS` 로 조회한 내용입니다.
불필요한 내용같습니다.

2017-09-22 09:06 UTC, antiline commented on _posts/2017-09-18-binlog-collector.md
> +![그림 5. Binlog Collector 설계](/blog/img/binlog05.png){: data-action="zoom" }
그림에서 master slave의 내용이 불필요한것 같습니다.

2017-09-22 09:06 UTC, antiline commented on _posts/2017-09-18-binlog-collector.md
> +그래도 실제 성능이 궁금하실 것 같아서 간단한 테스트 환경을 만들어서 성능을 측정해 보았습니다.
여기서는 그냥 운영중인 데이터를 공개하면 안되나요?
공개가 불가능하면, 이렇게 세세하기 보다는 대략적인것을 적어도 될것 같습니다.

2017-09-22 09:06 UTC, antiline commented on _posts/2017-09-18-binlog-collector.md
> +gtid_partition_max_count = 1000 // child BinlogOffsetRage 최대 개수
여기도 소스가 공개 안되어 있다면 변수명을 쓰는게 아니라 설명만 적어도 될것 같습니다.

2017-09-22 09:06 UTC, antiline commented on _posts/2017-09-18-binlog-collector.md
> +docker 기반으로 테스트 환경을 구축했고, 쉽게 검증할 수 있는 구조로 만들어 놓았기 때문에, 계속 테스트 하며 문제를 해결하고 개선할 예정입니다.
불필요한 문장같습니다.

2017-09-22 09:06 UTC, antiline commented on _posts/2017-09-18-binlog-collector.md
> +|동시 실행 개수 | Worker 총 시간|가장 오래 걸린 Worker 초
여기 테스트 결과 데이터가 쉽게 이해가 안되는것 같습니다.
워커 총시간이 전체 데이터 반영 수행 시간인건가요? 
가장 오래 걸린 워커는 여러개 워커, 여러번 수행 중 가장 오래걸린 시간인가요?

게다가 4개 이상인 경우는 의미 없는 테스트 데이터 같습니다.
해당 테스트 데이터를 바탕으로 뭘 도출 할 수 있는지 내용이 없습니다.

2017-09-22 09:06 UTC, antiline commented on _posts/2017-09-18-binlog-collector.md
> +![그림 6. Binlog Collector Partitioner 설계](/blog/img/binlog06.png){: data-action="zoom" }
그림이 너무 복잡한데 간단하게 수정될까요?

2017-09-22 09:09 UTC, antiline requested changes

2017-09-22 09:09 UTC, antiline commented on _posts/2017-09-18-binlog-collector.md
> +그래서 **범용적으로 DB 테이블의 변경 사항 추적** 이라는 단일 목적으로, DB의 CDC 기술을 검토하고 기존 환경에서 간단하게 활용했던 사례를 공유하겠습니다.
전반적으로 complete guide 처럼 서술되어 있는데 해당 글의 목적인가요?
`간단하게 활용했던 사례를 공유하겠습니다.` 라고 되어 있는데 글 목적과 내용이 안맞는것 같습니다.

2017-09-22 09:52 UTC, iamchanu commented
제가 시간이 없어서 이번주 내에 자세한 리뷰를 드리기는 힘들 것 같습니다.
그래서 문장 하나하나에 코멘트를 드리기보다는, 글 전반에 대한 인상을 말씀드리겠습니다.

저는 글에 집중하기가 어려워서 차분히 처음부터 끝까지 읽기가 좀 힘들었는데요, 그 이유가 뭘까 생각해 봤습니다.
1. 해결하려는 문제가 무엇인지 알기 어렵습니다. 어떤 점이 불편해서 이런 도구가 필요하게 됐는지, 와닿을만한 사례가 초반에 나와야 할 것 같습니다. 
이 부분이 글 처음에는 `안정적이고 신뢰성있는 플랫폼을 개발 및 유지보수`한다는 설명 정도로 넘어갔다가, 나중에 지연 시간 얘기가 나와서야 `한 시간 단위로 비공개된 도서에 대한 무결성을 체크하여 이상시 메일로 알리는 기능` 이라는 실제적인 사례가 나옵니다. 쌓은 binlog 를 가지고 무엇을 하려는지가 잘 이해가 되지 않으니, binlog 를 어떻게 쌓겠다는 얘기에 집중하기가 어렵습니다. 
2. 내용이 기술적으로 어렵습니다. MySQL 복제를 오랫동안 다뤄온 사람이 아니면 이해하기 어려울 것 같습니다. 처음에는 GTID 등의 개념에 대해서 어느정도 설명을 해 주는가 싶더니, 나중으로 갈수록 점점 깊은 내용이 나옵니다. 
이런 수준의 설명은 Binlog collector 를 실제로 사용하거나, 소스코드에 기여할 사람에게만 들려 줘도 될 것 같습니다. 블로그에 올려서 불특정 다수의 개발자에게 읽히려는 목적보다는, 사내 개발자들에게 프로젝트 히스토리 공유 정도의 목적이 어울리는 글입니다. 전문적인 설명을 최대한 자제하고, 일종의 스토리텔링이 될 수 있게 글을 써 보면 어떨까요?
3. 전반적으로 가독성이 떨어지는데, 영문이 너무 많이 섞여 있기 때문인 것 같습니다. 몇몇 불가피한 단어만 제외하고 전부 한글(한국어로 번역하거나, 발음을 한글로 쓰거나)로 바꾸면 가독성이 높아질 것 같습니다.

2017-09-24 14:33 UTC, earus requested changes

2017-09-24 14:33 UTC, earus commented on _posts/2017-09-18-binlog-collector.md
> +    * **장점:** 개발이 단순하고, 변경사항이 생길 경우 관련 이력테이블만 수정하면 됨
>변경사항이 생길 경우 관련 이력테이블만 수정하면 됨

이 부분이 잘 이해가 안가는데요.
테이블 구조가 바뀌었을 때 이력 테이블의 구조도 바꾸면 된다는 의미인가요?

2017-09-24 14:33 UTC, earus commented on _posts/2017-09-18-binlog-collector.md
> +    * 서버세팅: binlog-format:row 만 지원
맥락상 'row 방식 사용'이 더 정확한 표현 같습니다.

2017-09-24 14:33 UTC, earus commented on _posts/2017-09-18-binlog-collector.md
> +        * TableMap과 Write/Update/Delete 이벤트가 발생
'TableMap'이 binlog에서 Event_type이 'Table_map'인 것을 의미하는거죠?
binlog 이벤트를 살펴보지 않았던 사람이라면 무엇을 말하는지 추측하기 어려울 것 같습니다.

2017-09-24 14:33 UTC, earus commented on _posts/2017-09-18-binlog-collector.md
> +        * Query 이벤트가 발생
'Query 이벤트'가 무엇인지 추측하기 어렵습니다.
괄호에 어떤 정보가 담기는지 정도를 적어줘도 좋을 것 같습니다.

2017-09-24 14:33 UTC, earus commented on _posts/2017-09-18-binlog-collector.md
> +    *  다음과 같이 2가지로 시작 위치 가능
'시작 위치 가능' => '시작 위치 지정 가능' 정도로 바꾸는게 어떨까요?

2017-09-24 14:33 UTC, earus commented on _posts/2017-09-18-binlog-collector.md
> +실제 Binlog 이벤트들을 처음 보신 분들이 계실 수 있어서, 샘플 쿼리를 실행 한 후 `SHOW BINLOG EVENTS` 로 조회한 내용입니다.
음.. 제 생각에 binlog 이벤트를 살펴보지 않은 독자라면 이해에 도움이 되는 내용이라고 생각하는데요.
글 전체로 놓고 봤을 때 이 글을 읽는 독자에 대한 기대수준을 정하고 그에 맞춰서 한번 정리하는게 필요할 것 같습니다.

만약 이쪽 지식이 전혀 없는 독자를 대상으로 한다면 위 '그림 3. Binlog Event 흐름' 이전에 이 내용이 먼저 소개되면 더 자연스럽게 읽을 수 있을 것 같습니다.

2017-09-24 14:33 UTC, earus commented on _posts/2017-09-18-binlog-collector.md
> +한편, 특정 GTID 위치로부터 구동하였을 때 그 다음 GTID부터 이벤트 스트림을 가져오게 되는데(예: 0-1-7140로 시작하면, 다음 0-1-7141부터 가져옴),
이 부분은 글의 핵심 내용에서 조금 벗어나는 내용인 것 같습니다.

2017-09-24 14:33 UTC, earus commented on _posts/2017-09-18-binlog-collector.md
> +![그림 5. Binlog Collector 설계](/blog/img/binlog05.png){: data-action="zoom" }
'MariaDB (Another)'에서 'Another'의 의미가 애매한 것 같습니다.
변경사항을 저장하는 용도의 DB임을 좀 더 명시적으로 표현해주면 좋을 것 같습니다.

2017-09-24 14:33 UTC, earus commented on _posts/2017-09-18-binlog-collector.md
> +5. 모아진 이력 Rows를 JSON 데이터로 저장
JSON 데이터로 저장하는 이유는 무엇인가요?

2017-09-24 14:33 UTC, earus commented on _posts/2017-09-18-binlog-collector.md
> +3. **현재 GTID의 BinlogOffset의 잦은 위치 저장으로 인한 오버헤드**
이 항목이 이해가 잘 안갑니다. ㅎ

2017-09-24 14:33 UTC, earus commented on _posts/2017-09-18-binlog-collector.md
> +[3] [MySQL 이벤트 클래스와 유형](https://dev.mysql.com/doc/internals/en/event-classes-and-types.html)에는 Binlog 이벤트 클래스와 타입 정도들이 설명되어 있습니다.
https://dev.mysql.com/doc/internals/en/event-meanings.html

위 자료도 추가되면 좋을 것 같네요.

2017-09-24 14:33 UTC, earus commented on _posts/2017-09-18-binlog-collector.md
> +5. **Binlog 파일명을 못 찾는 문제**
이 문제가 어떤 경우인지 머리에 안그려지니 해결책으로 제시된 보정 처리 방식도 어떤 메커니즘 때문에 문제 없이 작동하는 것이 보장되는 것인지 알기가 어렵네요.

2017-09-24 14:33 UTC, earus commented on _posts/2017-09-18-binlog-collector.md
> +    * **해결:** GTID를 계산하지 않고 항상 `SELECT BINLOG_GTID_POS` 쿼리를 이용하여 변환하도록 수정
'GTID를 계산'하는건 어떤 것을 의미하나요?

2017-09-24 23:43 UTC, freekering commented
오늘까지 리뷰완료하겠습니다.

2017-09-25 08:55 UTC, freekering requested changes

2017-09-25 08:55 UTC, freekering commented on _posts/2017-09-18-binlog-collector.md
> +![그림 1. Logs For Infrastructure](/blog/img/binlog01.png){: data-action="zoom" }
(다른 사람이 그린 그림을 가져와서 쓰는게 좋고 나쁜지는 둘째치고라도) 글의 다른 그림들이랑 좀 결이 달라서 그냥 직접 그리는 편이 나을 것 같습니다.

2017-09-25 08:55 UTC, freekering commented on _posts/2017-09-18-binlog-collector.md
> +그러나 로그 기반의 구조는(오른쪽)는 CDC 기술을 이용해서 변경 데이터를 추출하고 메시지 큐에 넣어서 한 곳으로부터
위 두 줄의 `구조는(...)는` 부분에 괄호앞의 `는` 이 중복입니다.

2017-09-25 08:55 UTC, freekering commented on _posts/2017-09-18-binlog-collector.md
> +다양한 곳에서 사용하기 때문에 데이터를 관리하는 입장에서는 단순합니다.
`한 곳으로부터 다양한 곳에서 사용` 이라는 말의 뜻은 알겠는데 표현이 어색한 것 같습니다.

2017-09-25 08:55 UTC, freekering commented on _posts/2017-09-18-binlog-collector.md
> +불필요한 테이블을 SKIP 하는데 시간이 너무 많이 걸려서 Master의 현재 위치를 따라 잡지 못하고 계속 지연되는 현상이 발생하였습니다.
SKIP 이라는 단어로만 표현하면 구어체 느낌이 있어서 `불필요한 테이블에 대한 데이터를 거르는데` 정도로 순화하는게 좋을 것 같습니다.

2017-09-25 08:55 UTC, freekering commented on _posts/2017-09-18-binlog-collector.md
> +## 5. 병렬 Binlog Collector 설계 및 개발
글이 전체적으로 너무 긴 느낌이 있는데

1. 이 부분을 기점으로 해서 1,2부로 나누거나
2. 결과적으로는 이 내용 이후가 최종 결과물에 부합하므로 앞의 내용은 최대한 간략하게 줄이거나

하는게 좋을 거 같습니다.

2017-09-25 09:27 UTC, kobi97 commented
리뷰 진심으로 감사드립니다. 👍   
좀 더 생각해보고 의견 작성 및 추가 처리 진행하도록 하겠습니다.

2017-09-26 09:37 UTC, kobi97 commented on _posts/2017-09-18-binlog-collector.md
> +    * **장점:** 개발이 단순하고, 변경사항이 생길 경우 관련 이력테이블만 수정하면 됨
넵 맞습니다. 테이블 구조가 변경되면, 쌍으로 존재하는 변경 이력 테이블도 같이 수정해야 된다는 의미를 줄여서 작성하였습니다.

2017-09-26 09:41 UTC, kobi97 commented on _posts/2017-09-18-binlog-collector.md
> +        * TableMap과 Write/Update/Delete 이벤트가 발생
넵 Table_map 이벤트가 맞습니다. 저도 처음에 전혀 모르고, 실행해보니, TableMap
이벤트가 발생했고, 그 안에 관련 테이블 정보가 들어 있다는 것을 파악했습니다.

2017-09-26 09:50 UTC, kobi97 commented on _posts/2017-09-18-binlog-collector.md
> +한편, 특정 GTID 위치로부터 구동하였을 때 그 다음 GTID부터 이벤트 스트림을 가져오게 되는데(예: 0-1-7140로 시작하면, 다음 0-1-7141부터 가져옴),
이벤트 흐름 뿐만 아니라, 이벤트 흐름을 시작하게 하는 GTID 위치 구동 정보도 같이 넣었습니다.  (뒷부분에 계속 Binlog Collector를 구동하면 다음 GTID부터 된다는 내용이 반복되어 나와서요)

2017-09-26 09:53 UTC, kobi97 commented on _posts/2017-09-18-binlog-collector.md
> +5. 모아진 이력 Rows를 JSON 데이터로 저장
외부 라이브러리에서 값을 array 형태로 주는데, 데이터를 DB에 쉽게 적재 하기 위해서 JSON 형태로 저장했습니다. 뒷부분에 JSON 형태로 저장한 것을, db 정규화해서 컬럼으로 쪼개서 저장한다는 내용이 있어서 JSON이라고 명시했습니다.

2017-09-26 10:03 UTC, kobi97 commented on _posts/2017-09-18-binlog-collector.md
> +3. **현재 GTID의 BinlogOffset의 잦은 위치 저장으로 인한 오버헤드**
넵. append log 방식의 data가 존재하고, 해당 data를 스트리밍 방식으로 가져온다면, 장애발생시 재처리를 위해서 마지막으로 처리한 위치(offset)을 저장해야 합니다. 그런데 건마다 offset 위치를 db에 저장하면 오버헤드가 커서요.(메모리 db를 사용하기 환경히 넉넉치 않아서요)  그래서 500건마다 offset 위치를 갱신합니다. 다만 최종 저장된 offset 위치로부터 497번째 까지 처리하다가 장애가 난다면, 재처리시 다시 497개의 중복 데이터가 발생할 수 있지만, 중복 데이터를 제거하는 것은 어렵지 않다. 이런 내용입니다. ㅠ

2017-09-26 10:23 UTC, kobi97 commented on _posts/2017-09-18-binlog-collector.md
> +5. **Binlog 파일명을 못 찾는 문제**
위와 같은 상황은 아래와 같습니다.

Binlog 이벤트
```
MariaDBGTID(0-5-13124) (mariadb-bin.00044의 12313213)
TableMap       
WriteRow       
UpdateRow  
XID(0-5-13124)                    
FileRotate로 mariadb-bin.00045
MariaDBGTID(0-5-13125)
TableMap       
WriteRow     
XID(0-5-13125)               
```
실제 mariadb-bin.00044의 12313213 로 시작하면, 다음 GTID부터 시작됨으로(MariaDBGTID 0-5-13125 부터)FileRotate 이벤트가 발생하였다는 것을 모름.  따라서 현재 파일이 mariadb-bin.00044라고 생각하고 특정 위치에 대해서 gtid 변환시 에러 발생.

2017-09-26 10:25 UTC, kobi97 commented on _posts/2017-09-18-binlog-collector.md
> +    * **해결:** GTID를 계산하지 않고 항상 `SELECT BINLOG_GTID_POS` 쿼리를 이용하여 변환하도록 수정
아 GTID를 수동으로 계산한다는 의미였습니다. 수정하겠습니다.

2017-09-26 10:25 UTC, kobi97 commented on _posts/2017-09-18-binlog-collector.md
> +## 5. 병렬 Binlog Collector 설계 및 개발
기본적인 수정사항을 처리하고 나서 다시 정리해보겠습니다. 의견감사드립니다.

2017-09-26 11:13 UTC, kobi97 commented on _posts/2017-09-18-binlog-collector.md
> +데이터베이스의 **Change Data Capture(이하 CDC)**는 DB의 변경 이벤트들(Insert/Update/Delete/...)을 **단일 시퀀스 레코드 저장(이하 Append 로그)** 방식의 Binary 로그 파일에 저장하고
CDC라고 하는 기술을 먼저 소개하여, 사람들의 관심을 끌려고 순서를 변경하였습니다.

2017-09-26 11:15 UTC, kobi97 commented on _posts/2017-09-18-binlog-collector.md
> +CDC 기술을 이용하여 MariaDB의 테이블 변경사항을 추적하는 방법을 찾아보니,
해당 글은 MySQL로 Replication 세팅을 해본, Backend 개발자 대상으로 쓰여진 글로, 세부 내용 처리 이후에, 전체적으로 글을 다듬을 때, 다시 고민해보겠습니다. 의견 감사드립니다.

2017-09-26 11:26 UTC, kobi97 commented on _posts/2017-09-18-binlog-collector.md
> +여러 언어**(Java/Python/PHP/Node.js/Go)**로 구현된,
이 부분은 글을 다시 다듬을 때, 좀 고민을 해보겠습니다.

2017-09-26 11:33 UTC, kobi97 commented on _posts/2017-09-18-binlog-collector.md
> +![그림 4. SHOW BINLOG EVENTS 결과](/blog/img/binlog04.png){: data-action="zoom" }
동의합니다.

Binlog 이벤트가 
```
1. 트랜잭션 시작 ~ 끝이 있는 것(시작~끝) - gtid ~ xid(commit 이벤트) 
2. 트랜잭션 시작만 있는 형태(시작~) - gtid ~ ( no xid)
3. 트랜잭션과 상관없이 독립적으로 존재하는 것(트랜잭션 없음)
```
이런식으로 존재하는데... 좀 고민해보고 
그림에 내용 추가하도록 하겠습니다.

2017-09-26 11:35 UTC, kobi97 commented on _posts/2017-09-18-binlog-collector.md
> +![그림 5. Binlog Collector 설계](/blog/img/binlog05.png){: data-action="zoom" }
넵 그림에서 MariaDB(Master), MariaDB(Slave) -> MariaDB(Target) 으로 수정하겠습니다.

2017-10-07 04:39 UTC, kobi97 commented on _posts/2017-09-18-binlog-collector.md
> +데이터베이스의 **Change Data Capture(이하 CDC)**는 DB의 변경 이벤트들(Insert/Update/Delete/...)을 **단일 시퀀스 레코드 저장(이하 Append 로그)** 방식의 Binary 로그 파일에 저장하고
시작 부분에 글 독자층과 목적에 대해서 간단하게 추가 작성하였습니다.

2017-10-07 04:40 UTC, kobi97 commented on _posts/2017-09-18-binlog-collector.md
> +그래서 **범용적으로 DB 테이블의 변경 사항 추적** 이라는 단일 목적으로, DB의 CDC 기술을 검토하고 기존 환경에서 간단하게 활용했던 사례를 공유하겠습니다.
더 간단한 구조로 활용했던 사례로 수정하였습니다. (아키텍쳐가 간단하다는 의미였는데 글에 오해가 있었네요.)

2017-10-07 05:18 UTC, kobi97 commented on _posts/2017-09-18-binlog-collector.md
> +다양한 곳에서 사용하기 때문에 데이터를 관리하는 입장에서는 단순합니다.
`모든 데이터를 일괄적으로 메시지 큐에 넣어서 사용하기 때문에 데이터를 관리하는 입장에서는 단순해집니다.`
로 수정하였습니다.

2017-10-07 06:01 UTC, kobi97 commented on _posts/2017-09-18-binlog-collector.md
> +한편, 특정 GTID 위치로부터 구동하였을 때 그 다음 GTID부터 이벤트 스트림을 가져오게 되는데(예: 0-1-7140로 시작하면, 다음 0-1-7141부터 가져옴),
해당 글의 순서를 변경하고, 글이 자연스럽게 연결되도록 수정했습니다.

2017-10-16 08:56 UTC, kobi97 commented on _posts/2017-09-18-binlog-collector.md
> +여러 언어**(Java/Python/PHP/Node.js/Go)**로 구현된,
의견주신대로 언어 선택은 제거하였습니다. (이 부분 2줄을 빼놓고는 언어와 다 무관한 내용들이네요)

2017-10-16 08:57 UTC, kobi97 commented on _posts/2017-09-18-binlog-collector.md
> +gtid_partition_max_count = 1000 // child BinlogOffsetRage 최대 개수
설명기반으로 수정하였습니다.

2017-10-16 09:10 UTC, kobi97 commented on _posts/2017-09-18-binlog-collector.md
> +|동시 실행 개수 | Worker 총 시간|가장 오래 걸린 Worker 초
의견 주신대로 성능 측정 관련 표 제목 수정했습니다.
Worker 총 시간 -> 총 걸린 시간
가장 오래 걸린 Worker 초 -> 가장 오래 걸린 Worker 시간
그리고 실제 돌렸을 때, 16개의 경우는 의미가 없어서 삭제 했습니다.

보통 이런 류의 글에는 대략 성능이 얼마나 나오는지 알고 싶어어하는 독자가 있을 것 같아서, 작성하였습니다.
실제 유입되는 데이터와, 분석하고자 하는 테이블의 개수와 양의 따라서 달라질 수 있어서, 가장 기본적으로 테스트 환경을 작성하였습니다.  그리고 성능테스트는 병렬처리시 빠르고, 특정 개수 이상되면 tradeoff가 있다는 정도의 단순한 내용입니다. 하지만 docker 기반 테스트 환경을 구축해 놓았기 때문에, 추후 성능 측정의 개선이 가능하다는 내용을 덧붙였습니다.

2017-10-16 09:11 UTC, kobi97 commented on _posts/2017-09-18-binlog-collector.md
> +docker 기반으로 테스트 환경을 구축했고, 쉽게 검증할 수 있는 구조로 만들어 놓았기 때문에, 계속 테스트 하며 문제를 해결하고 개선할 예정입니다.
성능측정의 내용이 개인적으로 아쉬움이 있어서(시간상), 추후 개선이 가능하다는 의미로 (변명을) 넣었습니다.

2017-10-16 09:21 UTC, kobi97 commented on _posts/2017-09-18-binlog-collector.md
> +그래도 실제 성능이 궁금하실 것 같아서 간단한 테스트 환경을 만들어서 성능을 측정해 보았습니다.
하루치 데이터에 대해서 처음에 작성하였는데, 큰 의미가 없어 보여 내부리뷰에서 삭제되었습니다. 
테스트 환경 데이터에 대한 내용이 너무 세세하다는 의견이신가요? 추후 의미있는 성능테스트를 의해서, 실제 db나 binlog의 크기등을 일부러 자세히 적어보았는데... 불필요하다고 생각되면 삭제하겠습니다.

2017-10-16 10:01 UTC, kobi97 commented
작업 완료되면 따로 코멘트 드리겠습니다. (오늘밤에 완료예정입니다.)

2017-10-16 16:11 UTC, kobi97 commented
리뷰해주신 것들 최대한 반영했습니다. 재검토 요청드립니다. :)

2017-10-25 05:51 UTC, kobi97 commented
@antiline @earus @freekering @namenu @iamchanu 안녕하세요. 글을 전체적으로 많이 다듬었습니다. 시간되실 때 다시 한 번 리뷰 부탁드립니다. 항상 감사합니다.

2017-10-25 08:00 UTC, antiline requested changes

2017-10-25 08:00 UTC, antiline commented on _posts/2017-09-18-binlog-collector.md
> +MySQL Replication **Library**를 이용하면 DB 자체에 저장되어 있는 변경사항 이벤트를 추출하므로 추가 이력 데이터를 쌓을 필요가 없습니다.
오타가 아니라 **Library** 로 스타일 지정하신 이유가 있으신건가요?

2017-10-25 08:00 UTC, antiline commented on _posts/2017-09-18-binlog-collector.md
> +데이터베이스의 **Change Data Capture(이하 CDC)**는 DB의 변경 이벤트들(Insert/Update/Delete/...)을 **단일 시퀀스 레코드 저장(이하 Append 로그)** 방식의 Binary 로그 파일에 저장하고
밑에서는 (Insert/Update/Delete)  이렇게 하셨는데 둘 중 하나를 선택하시고 하나를 생략하는게 좋을것 같습니다.

2017-10-25 08:00 UTC, antiline commented on _posts/2017-09-18-binlog-collector.md
> +실제 Binlog 이벤트들을 처음 보신 분들이 계실 수 있어서, 샘플 쿼리를 실행 한 후 `SHOW BINLOG EVENTS` 로 조회한 내용입니다.
이 글은 GTID 기반의 MySQL Replication에 관심있는 Backend 개발자를 대상으로 합니다.  
라고 정의된거라면, 해당 내용은 생략해도 되지 않을까 생각됩니다.

2017-10-25 08:59 UTC, kobi97 commented on _posts/2017-09-18-binlog-collector.md
> +MySQL Replication **Library**를 이용하면 DB 자체에 저장되어 있는 변경사항 이벤트를 추출하므로 추가 이력 데이터를 쌓을 필요가 없습니다.
**MySQL Replication 라이브러리**를 실제 사용해서 개발해보겠다는 생각을 평소에 안해봐서, 강조를 위해서 넣었고, 영문은 한글로 변경하였습니다.

2017-10-25 08:59 UTC, kobi97 commented on _posts/2017-09-18-binlog-collector.md
> +데이터베이스의 **Change Data Capture(이하 CDC)**는 DB의 변경 이벤트들(Insert/Update/Delete/...)을 **단일 시퀀스 레코드 저장(이하 Append 로그)** 방식의 Binary 로그 파일에 저장하고
넵 수정했습니다.

2017-10-25 09:00 UTC, kobi97 commented on _posts/2017-09-18-binlog-collector.md
> +실제 Binlog 이벤트들을 처음 보신 분들이 계실 수 있어서, 샘플 쿼리를 실행 한 후 `SHOW BINLOG EVENTS` 로 조회한 내용입니다.
관심있는 개발자라도 Binlog 이벤트들을 직접 조회해보신 분들이 없을 것 같아서 넣었습니다. (저도 처음에 몰랐었습니다 :) )

2017-10-29 13:26 UTC, earus requested changes
수고 많으셨습니다!

2017-10-29 13:26 UTC, earus commented on _posts/2017-09-18-binlog-collector.md
> +글의 순서는 다음과 같이 진행됩니다.
'글의 순서는 다음과 같습니다'가 자연스러워 보입니다.

2017-10-29 13:26 UTC, earus commented on _posts/2017-09-18-binlog-collector.md
> +    * Client 접근 및 스키마 정보 조회 권한이 필요
'권한이'에서 '이'가 빠지는게 자연스러울 것 같습니다.

2017-10-29 13:26 UTC, earus commented on _posts/2017-09-18-binlog-collector.md
> +![그림 3. Binlog Event 흐름](/blog/img/binlog03.png){: data-action="zoom" }
우측 하단에 'Commt' 오타인 것 같습니다.
전에 없었던 이미지인 것 같은데 이해에 큰 도움이 될 것 같네요. :)

2017-10-29 13:26 UTC, earus commented on _posts/2017-09-18-binlog-collector.md
> +![그림 5. Binlog Collector 설계](/blog/img/binlog05.png){: data-action="zoom" }
`connect_array`와 `tablesOnly`, `databasesOnly`의 컨벤션이 달라 이상하게 느껴집니다.

2017-10-29 13:26 UTC, earus commented on _posts/2017-09-18-binlog-collector.md
> +        다음 GTID부터 이벤트를 가져올 때 File 변경 이벤트는 무시됨으로, 처음에 입력한 Binlog 파일명의 변경을 알지 못함
'무시되므로'가 맞는 표현입니다.

2017-10-29 13:53 UTC, freekering requested changes

2017-10-29 13:53 UTC, freekering commented on _posts/2017-09-18-binlog-collector.md
> +docker 3대: mariadb:10.0.27 db-master, db-slave, db-slave-slave
`docker 3대`라고 하기 보다는 `Docker 컨테이너 3개` 정도로 명확하게 표현하는게 좋겠습니다.

2017-10-29 13:53 UTC, freekering commented on _posts/2017-09-18-binlog-collector.md
> +docker 기반으로 테스트 환경을 구축했고, 쉽게 검증할 수 있는 구조로 만들어 놓았기 때문에, 계속 테스트 하며 문제를 해결하고 개선할 예정입니다.
`docker 기반` -> `Docker 컨테이너 기반` 으로 수정하는게 좋겠습니다. Docker도 엄연히 제품명이므로 표기에 신경써야 할 것 같습니다.

2017-10-30 00:51 UTC, kobi97 commented on _posts/2017-09-18-binlog-collector.md
> +![그림 5. Binlog Collector 설계](/blog/img/binlog05.png){: data-action="zoom" }
스네이크 표기법으로 변경하였습니다.

2017-10-30 00:57 UTC, merged