"Postman과 GitLab CI 연동" 글 작성
ridi/ridicorp.github.io pull request #49
Opened 2017-10-31 16:28 UTC by kyungmi

Postman을 선택해서 사용하게 된 이유와 Postman Test와 GitLab CI를 연동하는 방법에 대해서 다룬 글입니다.
내용은 평이합니다.

2017-11-01 06:15 UTC, antiline commented on _posts/2017-11-01-postman-gitlab-ci.md
> +- 환경(environment): 환경 별로 달라지는 변수들을 관리하기 위한 집합입니다. 환경에 설정된 변수들은 요청에서 `{{"{{variable_name"}}}}` 형태로 활용할 수 있습니다.
{{"{{variable_name"}}}} . 이부분 오타인가요??

2017-11-01 06:57 UTC, kyungmi commented on _posts/2017-11-01-postman-gitlab-ci.md
> +- 환경(environment): 환경 별로 달라지는 변수들을 관리하기 위한 집합입니다. 환경에 설정된 변수들은 요청에서 `{{"{{variable_name"}}}}` 형태로 활용할 수 있습니다.
@antiline 아뇨 Jekyll에서 지원하는 템플릿 문법 때문에, 저런식으로 escaping 해주지 않으면 화면에 표시되지 않더라고요. 의도했던 것은 `{{variable_name}}`입니다. Github에서는 잘 보여요.

2017-11-01 14:02 UTC, genesos approved these changes

2017-11-01 14:02 UTC, genesos commented on _posts/2017-11-01-postman-gitlab-ci.md
> +RESTful API를 작성하고 배포한 경험이 있는 분들이라면 API 문서화와 테스트에 대해 한 번쯤은 고민해 보셨을 것입니다. Postman은 API 테스트에 필요한 다양한 기능들을 제공하고 사용하기에 굉장히 편리한 UI를 가지고 있습니다. 또, Newman CLI와 결합하면, 각기 다른 환경에서 동일한 방법으로 테스트를 실행할 수 있습니다. 그래서 로
"다양한 기능들을 제공하고 사용하기에 굉장히 편리한"
 => "다양한 기능들을 제공하고 굉장히 편리한"
위의 의견을 조심스럽게 드리며, 그 외에는 의견드릴게 없는것 같습니다!

2017-11-06 02:23 UTC, antiline approved these changes

2017-11-06 06:56 UTC, namenu requested changes
글 중간중간에 등장하는 이미지 스크린샷에 너무 많은 GUI요소가 보여지고 있어서, 어디를 봐야할지 당황스러웠습니다. 화면에 익숙하지 않은 분들이라면 더 어렵게 느낄 것 같아요.

꼭 필요한 영역만 캡쳐하여 첨부하고, 중요한 영역만 강조되도록 이미지를 편집하면 훨씬 좋지 않을까 합니다.

2017-11-06 06:56 UTC, namenu commented on _posts/2017-11-01-postman-gitlab-ci.md
> +API는 사용자와의 약속입니다. 따라서 API를 개발하는 데 있어서 일관성 있는 설계와 기능 개발은 매우 중요한 요소입니다. 하지만 그보다 더 중요한 것은 잦은 변경에도 안정적으로 동작하는 버전을 지속적으로 제공하는 것입니다. 이것이 충족되려면 **문서화**와 **테스트**가 반드시 요구됩니다. 하지만 개발자들에게는 그만큼 귀찮은 짐이 되어버리는 경우가
"따라서 API를 개발하는 데 있어서 일관성 있는 설계와 기능 개발은 매우 중요한 요소입니다."

개발이라는 단어가 두 번 등장하는데, *구현*으로 바꾸어 표현하면 좋을 것 같습니다.

2017-11-06 06:56 UTC, namenu commented on _posts/2017-11-01-postman-gitlab-ci.md
> +이렇게 **문서화**와 **테스트**는 개발 전 영역에 걸쳐 가장 많이 반복되는 작업입니다. 기능을 새로 개발한다는 것은 문서를 업데이트하고 새로 테스트를 작성해야 한다는 것을 의미합니다. 개발자라면 분명히 이 부분의 오버헤드를 줄이고 싶을 것입니다.
위 그림만 보아서는 문서화가 테스트가 가장 많이 반복된다는 느낌을 받기 어려운데, 글이 그렇게 표현되어 있어서 어색합니다.

2017-11-06 06:56 UTC, namenu commented on _posts/2017-11-01-postman-gitlab-ci.md
> +Postman은 UI를 활용해 요청을 작성합니다. 특정 문법을 공부할 필요가 없으므로 빠르게 작업이 가능합니다. UI를 다루기 위한 러닝 커브가 거의 존재하지 않고, 빠른 작업을 위해 자동 완성과 같은 기능을 적극적으로 제공합니다. 그래서 개발 언어나 프레임워크를 모르더라도 문서를 이해하고 수정할 수 있습니다. 테스트 스크립트를 짜는 데 자바스크립트가 필
러닝 커브가 존재하지 않는다는 표현이 조금 어색합니다.
"UI가 단순하고 직관적이며" 정도로 포현하면 어떨까요?

2017-11-06 06:56 UTC, namenu commented on _posts/2017-11-01-postman-gitlab-ci.md
> +- 작성한 문서를 테스트로, 반대로 테스트를 바로 문서로 활용할 수 있습니다.[^1]
Jekyll에서 footnote 기능을 지원하지 않아 사용하지 않고 있었습니다.
실제 publish하고 보아도 잘 동작하나요?

2017-11-06 06:56 UTC, namenu commented on _posts/2017-11-01-postman-gitlab-ci.md
> +[GitLab](https://about.gitlab.com)이 설치형 Github라고 한다면, [GitLab CI](https://about.gitlab.com/features/gitlab-ci-cd/)는 [Travis CI](https://travis-ci.org/)에 비견될 수 있을 것입니다. GitLab에서는 CI/CD를 위한 파이프라인을 제공함으
Github -> GitHub

2017-11-06 06:56 UTC, namenu commented on _posts/2017-11-01-postman-gitlab-ci.md
> +- 환경(environment): 환경별로 달라지는 변수들을 관리하기 위한 집합입니다. 환경에 설정된 변수들은 요청에서 `{{"{{variable_name"}}}}` 형태로 활용할 수 있습니다.
쌍따옴표 위치가 잘못 되었습니다.

2017-11-06 06:56 UTC, namenu commented on _posts/2017-11-01-postman-gitlab-ci.md
> +- 컬렉션(collection): 요청(request)들을 묶는 가장 큰 단위입니다. 프로젝트 개념과 비슷하다고 생각하면 됩니다. 공유와 Postman Runner에서의 테스트는 컬렉션 단위로 이루어집니다.
가독성을 좀 더 높이기 위해, 설명 부분을 2-depth로 빼거나 표를 이용해보면 좋을 것 같습니다. 혹은 키워드에 볼드 처리를 해도 좋을 것 같고요.

2017-11-06 06:56 UTC, namenu commented on _posts/2017-11-01-postman-gitlab-ci.md
> +일단 테스트 용도로 컬렉션(PetStore Test)을 하나 생성합니다. 테스트를 구조화하는 방식은 개인마다 다르겠지만 저는 검증할 API 당 하나의 폴더를 생성했습니다. 그 하위에 (필요하다면) 공통 요청(예: 로그인)을 위한 폴더와 성공/실패 케이스에 대한 폴더를 생성합니다.
"(필요하다면)" 은 필요하지 않은 것 같습니다.

2017-11-06 07:01 UTC, kyungmi commented on _posts/2017-11-01-postman-gitlab-ci.md
> +이렇게 **문서화**와 **테스트**는 개발 전 영역에 걸쳐 가장 많이 반복되는 작업입니다. 기능을 새로 개발한다는 것은 문서를 업데이트하고 새로 테스트를 작성해야 한다는 것을 의미합니다. 개발자라면 분명히 이 부분의 오버헤드를 줄이고 싶을 것입니다.
그림에서 강조하기 어려운 부분을 글로 강조하는 것이 좋을 것 같습니다.
"문서화와 테스트가 가장 많이 반복된다"는 문장을 빼고 "기능을 새로 개발한다는 것은 문서를 업데이트하고 새로 테스트를 작성해야 한다는 것을 의미합니다." 문장을 앞으로 옮기는 게 좋겠네요.

2017-11-06 07:02 UTC, kyungmi commented on _posts/2017-11-01-postman-gitlab-ci.md
> +- 작성한 문서를 테스트로, 반대로 테스트를 바로 문서로 활용할 수 있습니다.[^1]
네 잘 동작합니다~

2017-11-06 07:04 UTC, kyungmi commented on _posts/2017-11-01-postman-gitlab-ci.md
> +Postman은 UI를 활용해 요청을 작성합니다. 특정 문법을 공부할 필요가 없으므로 빠르게 작업이 가능합니다. UI를 다루기 위한 러닝 커브가 거의 존재하지 않고, 빠른 작업을 위해 자동 완성과 같은 기능을 적극적으로 제공합니다. 그래서 개발 언어나 프레임워크를 모르더라도 문서를 이해하고 수정할 수 있습니다. 테스트 스크립트를 짜는 데 자바스크립트가 필
"러닝 커브가 거의 없다." 라는 말을 좀 더 설명적으로 적은 것인데, 적어주신대로 작성해도 뜻이 충분히 통할 것 같네요.

2017-11-06 07:05 UTC, kyungmi commented on _posts/2017-11-01-postman-gitlab-ci.md
> +- 환경(environment): 환경별로 달라지는 변수들을 관리하기 위한 집합입니다. 환경에 설정된 변수들은 요청에서 `{{"{{variable_name"}}}}` 형태로 활용할 수 있습니다.
지킬의 템플릿 문법 때문에 어쩔 수 없이 저렇게 작성해야 이스케이프 처리 되더라고요.

2017-11-06 07:08 UTC, kyungmi commented on _posts/2017-11-01-postman-gitlab-ci.md
> +일단 테스트 용도로 컬렉션(PetStore Test)을 하나 생성합니다. 테스트를 구조화하는 방식은 개인마다 다르겠지만 저는 검증할 API 당 하나의 폴더를 생성했습니다. 그 하위에 (필요하다면) 공통 요청(예: 로그인)을 위한 폴더와 성공/실패 케이스에 대한 폴더를 생성합니다.
스크린샷에서는 공통 요청을 위한 폴더가 나타나 있지 않아서 이 폴더를 생성하는 것은 옵셔널이라는 것을 표현하느라 저렇게 되었습니다. 차라리 스크린샷에 포함시키고 빼는 것으로 해 볼게요.

2017-11-06 13:16 UTC, earus approved these changes

2017-11-07 02:11 UTC, iamchanu requested changes
주제가 전반적으로
https://www.ridicorp.com/blog/2017/08/31/rest-api-testing/
와 상당부분 겹치는 것 같습니다.
(사실 이걸 보고 나니 저희가 한게 좀 삽질이라는 느낌이 듭니다...)

위 포스팅을 언급하면서 차이점 등에 대해 이야기하는 부분이 있는 것이 자연스럽지 않을까요?
그리고 위 포스팅 및 프레임웍의 작성자인 @jihungen 님도 리뷰어에 포함하는 것이 좋을 것 같습니다. ㅎㅎ

2017-11-07 02:11 UTC, iamchanu commented on _posts/2017-11-01-postman-gitlab-ci.md
> +그리고 각각의 폴더에 테스트를 위한 요청들을 생성합니다. 이 요청들은 다른 설정[^2]을 하지 않는 이상 눈에 보이는 그대로의 순서로 실행되며, 하나의 요청은 아래와 같은 순서로 실행됩니다.
이 **테스트 작성** 문단이 포스팅에서 가장 중요한 부분이라고 생각되는데, 정작 테스트를 작성하는 방법이 눈에 잘 들어오지 않습니다.
"인스트럭션"에 해당하는 문장 (`각각의 폴더에 테스트를 위한 요청들을 생성합니다`)과 팁 또는 구조 설명에 해당하는 문장(`하나의 요청은 아래와 같은 순서로 실행됩니다`)이 섞여 있어서 그런 것 같습니다.

**테스트 작성** 문단을 전체적으로, 불렛이나 넘버링을 이용해서 스텝 바이 스텝으로 따라할 수 있도록 변경하면 어떨까요?
인스트럭션은 최상위 불렛에 넣고, 팁 또는 부연설명은 하위 불렛에 넣거나 바깥으로 빼는 등으로 구조화하면 좋을 것 같습니다.

> - 각각의 폴더에 테스트를 위한 요청들을 생성합니다.
>   - 이 요청들은 다른 설정[^2]을 하지 않는 이상 눈에 보이는 그대로의 순서로 실행됩니다.

이런 식으로요.

2017-11-07 02:11 UTC, iamchanu commented on _posts/2017-11-01-postman-gitlab-ci.md
> +### GitLab CI 설정
이 문단도 위의 **테스트 작성**과 마찬가지로 스텝 바이 스텝으로 작성되면 좋을 것 같습니다.

2017-11-07 03:02 UTC, kyungmi commented on _posts/2017-11-01-postman-gitlab-ci.md
> +그리고 각각의 폴더에 테스트를 위한 요청들을 생성합니다. 이 요청들은 다른 설정[^2]을 하지 않는 이상 눈에 보이는 그대로의 순서로 실행되며, 하나의 요청은 아래와 같은 순서로 실행됩니다.
아무래도 글이 딱딱하게 보이지 않게 하기 위해서 좀 풀어서 쓴 측면이 있는데, 오히려 가독성을 해치게 된 것 같습니다. 의견 반영해서 다시 작성해 볼게요~

review summary에 주신 답변은 직접적으로 댓글을 달 수가 없어서 여기에 말씀드리면, 원래는 예전에 작성하신 글 때문에 이 주제로 작성하지 않으려고 했었습니다. 그런데, 상관 없다는 답변을 들어서 얘기가 된 부분인줄 알았네요. 아무래도 언급을 하게 되면, 왜 작성하신 프레임워크를 쓰지 않게 되었는지에 대한 부연 설명이 들어가야 하는데 그 부분을 작성하기가 좀 애매하더라고요. ㅠㅠ

언급이 꼭 필요하다면 어떻게 접근하는 것이 좋을지 좀 더 고민을 해보겠습니다.

2017-11-07 03:06 UTC, freekering commented on _posts/2017-11-01-postman-gitlab-ci.md
> +Postman은 UI를 활용해 요청을 작성합니다. 특정 문법을 공부할 필요가 없으므로 빠르게 작업이 가능합니다. UI를 다루기 위한 러닝 커브가 거의 존재하지 않고, 빠른 작업을 위해 자동 완성과 같은 기능을 적극적으로 제공합니다. 그래서 개발 언어나 프레임워크를 모르더라도 문서를 이해하고 수정할 수 있습니다. 테스트 스크립트를 짜는 데 자바스크립트가 필
러닝 커브는 있고 없고의 문제가 아니라(항상 있는 것이고) 그 모양이 어떻게 생겼느냐의 문제이니까요. 그 부분이 어색하게 느껴진다고 하신거 같습니다.

2017-11-07 05:45 UTC, iamchanu commented on _posts/2017-11-01-postman-gitlab-ci.md
> +그리고 각각의 폴더에 테스트를 위한 요청들을 생성합니다. 이 요청들은 다른 설정[^2]을 하지 않는 이상 눈에 보이는 그대로의 순서로 실행되며, 하나의 요청은 아래와 같은 순서로 실행됩니다.
네. 일단 저랑 지훈님은 이 포스팅에 대해서 이야기를 들은 바는 없습니다. 그리고 경미님도 과거 지훈님 포스팅에 대해서 혹시 생각하지 못하고 계셨을까봐 의견을 드렸습니다.
하지만 경미님이랑 선국님이 이미 과거 포스팅의 존재와 내용이 겹치는 부분에 대해서 인지하고 계셨고, 상관없다는 판단을 내리셨다고 하니, 저희가 뭐라 더 말씀드릴 부분은 아닌것 같네요. ㅎㅎ 
사실 제가 생각해도 구체적으로 뭐라고 언급을 해야 할지가 애매한 부분인 것 같습니다. ㅠㅠ

어쨌든 저는 과거에 그런 포스팅이 있었으니 고려해야 한다...라고 환기 차원에서 말씀드렸다고 이해하시면 좋겠습니다.
아무래도 회사 이름으로 같은 공간에 나가는 포스팅들이다보니, 어느정도 서로 일관성이 있어야 한다는 생각이 들기도 해서요. @namenu CTO님의 의견도 궁금합니다.

2017-11-07 05:47 UTC, freekering commented on _posts/2017-11-01-postman-gitlab-ci.md
> +그리고 각각의 폴더에 테스트를 위한 요청들을 생성합니다. 이 요청들은 다른 설정[^2]을 하지 않는 이상 눈에 보이는 그대로의 순서로 실행되며, 하나의 요청은 아래와 같은 순서로 실행됩니다.
찬우님이나 지훈님께는 따로 의견을 여쭤보진 않았었는데요. 저도 찬우님이 우려하신 부분에 대한 걱정이 있었지만 글이 연달아 있지만 않으면 괜찮을 것 같다고 생각했고 CTO님에게 최종적으로 의견을 물었을 때 괜찮을 것 같다고 하셔서 일단 진행은 하게됐습니다.

2017-11-07 06:17 UTC, jihungen commented on _posts/2017-11-01-postman-gitlab-ci.md
> +그리고 각각의 폴더에 테스트를 위한 요청들을 생성합니다. 이 요청들은 다른 설정[^2]을 하지 않는 이상 눈에 보이는 그대로의 순서로 실행되며, 하나의 요청은 아래와 같은 순서로 실행됩니다.
제가 테스팅 프레임워크를 개발했을 때 **Postman**에 대해서 조사를 했었습니다. 하지만, 저희 팀에서 사용하기에는 무료 버전의 `API calls / month`가 1,000 calls로 너무 적다고 생각하여 큰 기능을 사용하는 것도 아닌데 유료 버전을 쓸 필요가 있나 하는 생각이었습니다; 현재 데이터팀에서 추천 API를 모니터링 할 때는 5분당 80개의 API calls를 만들어내니, 하루만해도 23,040 API calls를 사용합니다. (블로그에도 비슷한 내용이 언급되어 있습니다.)

위에 말씀 드린 부분이 제가 개발한 테스팅 프레임워크를 사용하는 이유가 될 것 같습니다 :) 그리고, 같은 API 주소에 대해서 전달하는 parameter를 손쉽게 바꿀 수 있다는 점 정도가 있지 않을까 생각합니다. (이 부분은 자세히 확인을 해보지 않았기 때문에 틀릴 수도 있습니다.) 그 외에는 아무래도 상용 툴인 **Postman**이 여러모로 나은 것 같습니다 :)

그래서, 제가 적었던 블로그에 대한 언급이 필요하다고 생각하셔서 만약 하게 되신다면, 그 부분을 얘기하시면 될 것 같습니다. 즉, 테스트 케이스 작성의 편리함이나 장애가 발생했을 때 확인할 수 있는 Web UI 등의 강점 (쉬운 문서화 등 ...) 을 얘기할 수 있고, 저희 팀에서와 같은 양의 API calls가 필요하지 않다면 **Postman**이 더 합리적인 선택이라는 것도 얘기할 수 있다고 생각합니다.

2017-11-07 06:32 UTC, kyungmi commented on _posts/2017-11-01-postman-gitlab-ci.md
> +그리고 각각의 폴더에 테스트를 위한 요청들을 생성합니다. 이 요청들은 다른 설정[^2]을 하지 않는 이상 눈에 보이는 그대로의 순서로 실행되며, 하나의 요청은 아래와 같은 순서로 실행됩니다.
@jihungen 답변 감사합니다~

그런데 제가 작성한 글에서는 Postman은 스펙 작성용으로만 사용하고 CLI를 사용해 따로 비용을 지불하지 않고 구동시키는 방법을 다루고 있어서 말씀해주신 논점은 다루기가 조금 힘들 것 같습니다 ㅠ (API call 수 제한이 있다는 것은 말씀해주셔서 알았네요.) 모니터링 기능을 사용한다거나 하면 비용이 문제가 되는 부분이 있겠군요...

그러고 보니 API 수가 굉장히 많고, 다루는 데이터가 복잡하다면 UI 작성 툴이 오히려 더 불편하겠다는 생각은 듭니다.
고민해보고 다시 작성해볼게요.

2017-11-07 08:40 UTC, namenu commented on _posts/2017-11-01-postman-gitlab-ci.md
> +그리고 각각의 폴더에 테스트를 위한 요청들을 생성합니다. 이 요청들은 다른 설정[^2]을 하지 않는 이상 눈에 보이는 그대로의 순서로 실행되며, 하나의 요청은 아래와 같은 순서로 실행됩니다.
네, 이미 언급된대로 Postman과 `lightweight-rest-tester`는 사용하게된 동기가 다릅니다.

문제는 누군가가 "테스팅 프레임워크 개발해놓고 자기들도 안쓰네" 이런 느낌을 가질까봐 우려가 된다는 것인데요. 두 글을 모두 읽은 사람이라면 용도가 다르다는 점을 인지할 수 있을 것입니다. (@jihungen님 포스팅에는 Postman이 언급되고 있기도 하고요)

그럼에도 불구하고 본 포스팅의 어딘가에 해당 글에 대한 언급이 있으면 서로 홍보도 되고 좋겠지만, 이 때문에 흐름이 어색해진다면 굳이 없어도 된다고 생각합니다.

2017-11-07 10:14 UTC, kobi97 commented on _posts/2017-11-01-postman-gitlab-ci.md
> +[Postman](https://www.getpostman.com/)은 2012년에 첫걸음을 뗀 RESTful API 테스트 도구입니다.
[제안] 경미님 요청으로 남깁니다. `RESTful API 테스트 도구` -> `REST Client 도구`  (홈페이지에도 그렇게 나와 있어서요. 참고적으로 현재는 API 개발을 위한 툴셋이라는 표현을 쓰네요)

2017-11-07 10:19 UTC, kobi97 commented on _posts/2017-11-01-postman-gitlab-ci.md
> +GitLab CI도 Travis CI와 같이 YAML 형태의 설정 파일(`.gitlab-ci.yml`)을 처리합니다. 이 파일에는 사용자가 설정할 작업을 실행할 Docker 컨테이너(`image`, `service` 섹션)과 각 작업에서 실행할 스크립트를 정의합니다.
`실행할 Docker 컨테이너(...)과 각 작업에서 실행할 스크립트를 정의합니다.` 이 부분 조사 또는 ()가 잘못된 것 같습니다.

2017-11-07 12:47 UTC, kobi97 commented
글 잘보았습니다. :) 한가지 의견을 드리면 postman을 사용하는 이유가 문서화와 테스트 때문이라고 하셨는데, 문서화 부분에 대해서도 좀 더 구체적으로 설명을 해주시면 좋을 것 같습니다. 예를들면 api 스펙 문서 그림 또는 api 스펙 배포 과정과 같은 것들이 있으면 좋을 것 같습니다.

2017-11-07 16:19 UTC, kyungmi commented
글을 작성하는 데 사용한 노트북 수리를 맡긴 상태라(생각을 못 했네요) 글의 예제를 작성하기 위해 생성한 Postman 컬렉션을 현재 사용할 수 없는 상태입니다... 문서화 관련한 스크린샷 등은 노트북을 받게 되면 다시 작성하거나, 뷰어팀에서 사용하고 있는 컬렉션을 이용해 보여주어야 할 것 같습니다.

`lightweight-rest-tester`와 관련한 내용은 어떻게 풀어갈지 고민중입니다.

나머지 리뷰 내용들은 반영했습니다.

2017-11-07 16:40 UTC, namenu approved these changes
👍

2017-11-08 02:10 UTC, kyungmi commented
@iamchanu @jihungen 
`lightweight-rest-tester`를 언급하는 내용을 넣어보았습니다. "모니터링에 초점을 두고 만들어진 프레임워크여서 아쉽게도 API 스펙의 세세한 부분을 검증해야 하는 테스트를 위한 대안이 될 수 없었다."고 소개했는데, 적합하지 않다면 빼는 것이 좋을 것 같습니다.

2017-11-08 02:18 UTC, freekering requested changes

2017-11-08 02:18 UTC, freekering commented on _posts/2017-11-01-postman-gitlab-ci.md
> +최근에 뷰어 팀에서는 API 서버의 소스 구조를 대폭 개편하는 작업을 진행했습니다. 타 팀의 코드와 함께 동작하고 있던 뷰어 API 소스를 분리해 따로 서비스 환경을 구축하고, 정리되지 않았던 에러 응답 방식을 체계화했으며, 그와 함께 PHP 기반이었던 코드를 Node.js 기반으로 옮기는 API v2 작업도 진행 중이었습니다.
`뷰어팀`, `데이터팀` 으로 붙여쓰는게 좋겠습니다.

2017-11-08 02:20 UTC, kyungmi commented on _posts/2017-11-01-postman-gitlab-ci.md
> +최근에 뷰어 팀에서는 API 서버의 소스 구조를 대폭 개편하는 작업을 진행했습니다. 타 팀의 코드와 함께 동작하고 있던 뷰어 API 소스를 분리해 따로 서비스 환경을 구축하고, 정리되지 않았던 에러 응답 방식을 체계화했으며, 그와 함께 PHP 기반이었던 코드를 Node.js 기반으로 옮기는 API v2 작업도 진행 중이었습니다.
@freekering 저도 처음엔 붙여 썼는데, 문법 검사기에 돌려보니 띄어 쓰는게 맞다고 나와서 바꿨어요 ㅋㅋ

2017-11-08 02:20 UTC, jihungen commented
@kyungmi 
> API 스펙의 세세한 부분을 정확히 검증하기에는 표현에 제한이 있었고

요 부분에 대해서 자세히 설명해 주실 수 있나요? 앞의 내용을 보면 **허용되지 않은 응답 데이터** 외에 뭔가 다른 것을 말씀하시는 것 같은데, 예를 들어서 설명해주시면 좋을 것 같습니다.

그 외에는 이견이 없습니다 :) 저도 CTO님의 코멘트의 이 부분:
> 문제는 누군가가 "테스팅 프레임워크 개발해놓고 자기들도 안쓰네" 이런 느낌을 가질까봐 우려가 된다는 것인데요.

만 해결이 되면 괜찮다고 생각합니다.

2017-11-08 02:31 UTC, kyungmi commented
@jihungen 
제가 제대로 확인을 못한 걸지도 모르겠는데, 예를 들어서, 응답 JSON 중에 어떤 필드 값이 특정한 값에 exactly match 되는 경우를 체크할 수 있나요? Create/Update 타입의 API를 체크할 때 반영한 값과 일치하는지를 테스트하기 위해 정확한 값을 체크해야 하는 경우가 있었고요. 에러 케이스의 경우에도 각 상황에 따라 에러 코드를 정확히 체크해야 했었습니다.
API 테스트의 경우에는 시나리오가 있기 때문에 테스트 케이스 이름 같은 경우에도 의미를 정확히 알 수 있게 따로 정할 수 있었다면 좋았을 것 같아요.

2017-11-08 02:34 UTC, iamchanu commented on _posts/2017-11-01-postman-gitlab-ci.md
> +최근에 **데이터 팀에서 만든 [lightweight-rest-tester](/blog/2017/08/31/rest-api-testing/)**가 있었지만 아쉽게도 대안이 될 수 없었습니다. 모니터링을 목적으로 만들어졌기 때문에 서버의 비정상적인 상태(잘못된 응답 형식, 허용되지 않은 응답 데이터, 시간 초과 등)을 판별하기엔 적합했지만 API 스펙의 세
> API 스펙의 세세한 부분을 정확히 검증하기에는 표현에 제한이 있었고

요 부분을 조금 부연해 보겠습니다.

lightweight-rest-tester 는 실제 운영중인 서비스를 모니터링하기 위한 것이기 때문에, 서비스가 정상적이라고 판단할 만한 최소한의 요구조건 (json 형식 및 응답 데이터의 갯수)을 표현해야 했고, 이를 위해 JSONSchema 를 이용했습니다. JSONSchema 의 단점은 익숙하지 않은 사람이 작성 및 편집하기가 조금 어렵다는 것인데요. 우리의 목적은 서비스의 정상 여부를 판단하는 것이기 때문에 그 요구조건이 자주 변경되지 않고, 그래서 JSONSchema 의 단점은 별로 중요하지 않았습니다.

뷰어팀 CI 의 경우는 API 의 스펙이 자주 변경되고, 검증해야 할 요소들이 복잡하기 때문에, 쉽고 표현력이 풍부한 자바스크립트로 테스트를 작성할 수 있는 Postman 이 적합했던 것 같습니다.

2017-11-08 02:41 UTC, kyungmi commented on _posts/2017-11-01-postman-gitlab-ci.md
> +최근에 **데이터 팀에서 만든 [lightweight-rest-tester](/blog/2017/08/31/rest-api-testing/)**가 있었지만 아쉽게도 대안이 될 수 없었습니다. 모니터링을 목적으로 만들어졌기 때문에 서버의 비정상적인 상태(잘못된 응답 형식, 허용되지 않은 응답 데이터, 시간 초과 등)을 판별하기엔 적합했지만 API 스펙의 세
설명해주신 내용을 본문에 반영하면 내용에서 많이 벗어나게 되는 것 같아서, 의도하신 내용이 드러날 수 있도록 글을 좀 더 정리해 보겠습니다.

2017-11-08 02:50 UTC, jihungen commented
@kyungmi 
방금 @iamchanu 님이 코멘트 주신 것처럼 **lightweight-rest-tester**는 JSONSchema를 사용하고 있습니다. 그 코멘트에서 얘기한 JSONSchema의 단점들과 @kyungmi 님이 말씀해주신 부분들이 지금의 JSONSchema의 한계입니다; 저도 확인해보니 다음 버전의 JSONSchema에서 `const`라는 이름으로 지원할 예정이라고 합니다.

> API 스펙의 세세한 부분을 정확히 검증하기에는 표현에 제한이 있었고

이 어떤 것을 말씀하시는지 궁금해서 여쭤 봤었습니다.

> API 테스트의 경우에는 시나리오가 있기 때문에 테스트 케이스 이름 같은 경우에도 의미를 정확히 알 수 있게 따로 정할 수 있었다면 좋았을 것 같아요.

네, 이건 추가하는 것이 좋을 것 같습니다 :)

2017-11-09 02:00 UTC, kyungmi commented
@kobi97 문서화 관련 내용 간략하게 추가했습니다~

2017-11-09 02:01 UTC, kyungmi commented on _posts/2017-11-01-postman-gitlab-ci.md
> +최근에 뷰어 팀에서는 API 서버의 소스 구조를 대폭 개편하는 작업을 진행했습니다. 타 팀의 코드와 함께 동작하고 있던 뷰어 API 소스를 분리해 따로 서비스 환경을 구축하고, 정리되지 않았던 에러 응답 방식을 체계화했으며, 그와 함께 PHP 기반이었던 코드를 Node.js 기반으로 옮기는 API v2 작업도 진행 중이었습니다.
수정했습니다~

2017-11-09 02:02 UTC, kyungmi commented on _posts/2017-11-01-postman-gitlab-ci.md
> +최근에 **데이터 팀에서 만든 [lightweight-rest-tester](/blog/2017/08/31/rest-api-testing/)**가 있었지만 아쉽게도 대안이 될 수 없었습니다. 모니터링을 목적으로 만들어졌기 때문에 서버의 비정상적인 상태(잘못된 응답 형식, 허용되지 않은 응답 데이터, 시간 초과 등)을 판별하기엔 적합했지만 API 스펙의 세
@iamchanu @jihungen 글 내용 조금 수정해 봤습니다. 확인 부탁드립니다~

2017-11-09 02:10 UTC, jihungen commented on _posts/2017-11-01-postman-gitlab-ci.md
> +최근에 **데이터팀에서 만든 [lightweight-rest-tester](/blog/2017/08/31/rest-api-testing/)**가 있었지만 아쉽게도 대안이 될 수 없었습니다. 모니터링을 목적으로 만들어졌기 때문에 서버가 정상적인 상태라고 확인할 수 있는 최소한의 조건(허용된 응답 코드를 반환하는지, JSONSchema로 표현되는 응답 형식을
> 정해진 시간 내에 응답을 하는지 등의

"정해진 시간 내에 응답을 하는지 등"이 아닐까요?

2017-11-09 02:11 UTC, jihungen commented on _posts/2017-11-01-postman-gitlab-ci.md
> +운영 환경이 바뀌는 데다 구조적인 변화가 많이 있었기 때문에 전체 API가 잘 동작하는지, 에러 케이스에 요구되는 응답을 정확히 주는지에 대한 검증이 필요했습니다. 그리고 이때까지 유닛 테스트로만 코드를 검증했고, 따로 작성된 API 테스트가 없었기 때문에 API 테스트를 새로 작성해야 했습니다. 그 테스트 코드마저도 PHP와 Node.js 이중으로 작성
> 에러 케이스에 요구되는 응답을
"에러 케이스에서 요구하는 응답을" 이 조금 더 자연스럽지 않을까요?

2017-11-09 02:17 UTC, jihungen commented on _posts/2017-11-01-postman-gitlab-ci.md
> +최근에 **데이터 팀에서 만든 [lightweight-rest-tester](/blog/2017/08/31/rest-api-testing/)**가 있었지만 아쉽게도 대안이 될 수 없었습니다. 모니터링을 목적으로 만들어졌기 때문에 서버의 비정상적인 상태(잘못된 응답 형식, 허용되지 않은 응답 데이터, 시간 초과 등)을 판별하기엔 적합했지만 API 스펙의 세
@kyungmi 
네, 확인했습니다! 의도가 잘 전달되는 것 같습니다 :)

해당 부분에서 어색하다고 생각하는 부분에 대해서 코멘트를 드렸는데, 혹 동의하지 않으시면 굳이 반영하실 필요는 없는 것 같습니다.

2017-11-09 02:26 UTC, iamchanu approved these changes

2017-11-09 02:28 UTC, freekering approved these changes

2017-11-09 02:53 UTC, kyungmi commented on _posts/2017-11-01-postman-gitlab-ci.md
> +최근에 **데이터팀에서 만든 [lightweight-rest-tester](/blog/2017/08/31/rest-api-testing/)**가 있었지만 아쉽게도 대안이 될 수 없었습니다. 모니터링을 목적으로 만들어졌기 때문에 서버가 정상적인 상태라고 확인할 수 있는 최소한의 조건(허용된 응답 코드를 반환하는지, JSONSchema로 표현되는 응답 형식을
아 '조건'을 수식한다고 무의식중에 생각한 것 같아요. 그래서 저렇게 '의'가 남았군요. ㅋㅋ 수정할게요

2017-11-09 02:54 UTC, kyungmi commented on _posts/2017-11-01-postman-gitlab-ci.md
> +운영 환경이 바뀌는 데다 구조적인 변화가 많이 있었기 때문에 전체 API가 잘 동작하는지, 에러 케이스에 요구되는 응답을 정확히 주는지에 대한 검증이 필요했습니다. 그리고 이때까지 유닛 테스트로만 코드를 검증했고, 따로 작성된 API 테스트가 없었기 때문에 API 테스트를 새로 작성해야 했습니다. 그 테스트 코드마저도 PHP와 Node.js 이중으로 작성
네 쓸데없는 피동형 문장인 것 같습니다.

2017-11-09 05:58 UTC, merged