리디북스 PAPER PRO UI 디자인하기
ridi/ridicorp.github.io pull request #67
Opened 2018-08-06 09:05 UTC by jihyeleee

- 이미지 업로드 완료
- 현우님이 주신 수정 사항 외에 위키에서 받은 피드백 반영 완료

2018-08-06 12:35 UTC, namenu reviewed
많이 개선되었네요.
피드백 드린 부분만 확인 부탁드립니다!

2018-08-06 12:35 UTC, namenu commented on _posts/2018-07-25-paper-pro-ui-design.md
> +- Professional
키워드를 영어로 표현할 필요가 있을까요? 😅

2018-08-06 12:35 UTC, namenu commented on _posts/2018-07-25-paper-pro-ui-design.md
> +
`다운로드↓`의 화살표가 어색하게 느껴지는데요, Markdown의 footer로 나타내면 어떨까요?

2018-08-06 12:35 UTC, namenu commented on _posts/2018-07-25-paper-pro-ui-design.md
> +물론 처음부터 화면 전환도 느리고 잔상이 남아서 주로 블랙(#000000)만 사용해야 하는 흑백의 전자 잉크 기기를 디자인하는 일이 쉽진 않았습니다. 하지만 모든 제약 사항을 고려한 작업이 '책 읽기에 최적화된 기기'를 만드는 일이여서 즐겁게 일할 수 있었습니다.
바로 위의 문단과 이 내용을 하나로 합치면서 내용을 조금 줄이면 어떨까요?
내용이 조금 늘어지는 느낌이 들었습니다.
(`즐거웠다`는 표현이 두 번 등장하는 것도 어색하게 느껴졌습니다)

2018-08-06 12:35 UTC, namenu commented on _posts/2018-07-25-paper-pro-ui-design.md
> +> Onboarding is a virtual unboxing experience that helps users get started with an app.
피드백을 드렸던 것 같긴 한데요 ㅎㅎ
원문과 번역문의 의미가 불일치하는 것은 지양해야 한다는 생각이 드네요.

`that helps~` 부분을 지우거나 번역을 추가하는 것이 좋겠습니다.

2018-08-07 01:10 UTC, jihyeleee commented on _posts/2018-07-25-paper-pro-ui-design.md
> +- Professional
'키워드'는 영어지만 자주 사용하는 외래어라서 괜찮지 않을까요? '핵심어'라고 한글로 쓸 수 있지만 '키워드'를 현업에서 더 많이 쓰고 익숙해서요.

2018-08-07 01:18 UTC, jihyeleee commented on _posts/2018-07-25-paper-pro-ui-design.md
> +
footnote 말씀하시는건가요? :)

2018-08-07 01:28 UTC, jihyeleee commented on _posts/2018-07-25-paper-pro-ui-design.md
> +물론 처음부터 화면 전환도 느리고 잔상이 남아서 주로 블랙(#000000)만 사용해야 하는 흑백의 전자 잉크 기기를 디자인하는 일이 쉽진 않았습니다. 하지만 모든 제약 사항을 고려한 작업이 '책 읽기에 최적화된 기기'를 만드는 일이여서 즐겁게 일할 수 있었습니다.
> PAPER PRO 이전 모델은 부분적으로 개선하는 일이 주였습니다. 하지만 PAPER PRO는 새로 출시하는 제품이어서 제품이 꺼져있는 순간부터 사용 후 종료하기까지, 모든 과정에 참여할 수 있었습니다. 전반인 사용 시나리오를 검토하고 UI를 디자인하는 일은 뿌듯하고 즐거웠습니다.

이렇게 한 문단으로 수정하려고 합니다!

2018-08-07 01:28 UTC, jihyeleee commented on _posts/2018-07-25-paper-pro-ui-design.md
> +> Onboarding is a virtual unboxing experience that helps users get started with an app.
넵 제거했습니다.

2018-08-08 05:19 UTC, namenu commented on _posts/2018-07-25-paper-pro-ui-design.md
> +- Professional
아, 키워드 자체가 아니고요 여기 아래에 나열된 항목들이요.
핵심어는 ㅎㅎㅎ

2018-08-08 07:12 UTC, jihyeleee commented on _posts/2018-07-25-paper-pro-ui-design.md
> +- Professional
앗 그런 뜻이었군요. 디자인 컨셉 잡을 때 영어 단어를 많이 써서 자연스럽게 썼던 것 같아요. 한글로 변경하겠습니다.

2018-08-08 08:53 UTC, freekering requested changes

2018-08-08 08:53 UTC, freekering commented on _posts/2018-07-25-paper-pro-ui-design.md
> +2017년 12월, PAPER PRO가 출시되었습니다. 눈에 띄는 변화는 크기입니다. 6인치에서 7.8인치로 켜졌습니다. 페이지를 넘기는 물리 버튼도 양쪽에 하나씩 더 추가되어 총 4개의 버튼으로 페이지를 넘길 수 있습니다. 이 밖에도 색 온도 조절 기능과 자주 쓰는 기능을 설정할 수 있는 ‘퀵 버튼’도 추가되었습니다. 이런 여러 가지 하드웨어의 변화에
6인치, 7.8인치는 정확히는 화면 크기 이므로 `눈에 띄는 변화는 화면 크기입니다.` 혹은 `화면이 6인치에서 7.8인치로 커졌습니다.`  정도로 수정하는게 정확할 것 같습니다.

`이 밖에도 색온도 조절 기능과 자주 쓰는 기능을 설정할 수 있는~` 이라고 되어있어서 마치 '퀵 버튼'으로 색 온도 조절 기능을 설정한다는 것처럼 느껴지기도 합니다. 색 온도 조절 기능은 아래 본문에서도 소개하고 있으므로 좀 더 정확히 `색 온도 조절 기능이 추가되고 자주 쓰는 기능을 설정할 수 있는~` 으로 표현하는게 어떨까 합니다.

2018-08-08 08:53 UTC, freekering commented on _posts/2018-07-25-paper-pro-ui-design.md
> +결정한 이유는 일단 너무 많은 선택지가 있을 경우 하나하나 눈에 들어오지 않고 어떤 걸 택해야 할지 망설이게 되고 그만큼 고민해야 합니다.
문장 호응 관계가 어색합니다. `고민해야 하기 때문입니다.` 정도로 끝나야 할 것 같습니다.

2018-08-08 08:53 UTC, freekering commented on _posts/2018-07-25-paper-pro-ui-design.md
> +이전 모델과 다르게 PAPER PRO에는 전원 버튼, 페이지 넘김 버튼 외에 하나의 버튼이 더 있습니다. 버튼의 이름은 ‘퀵 버튼'으로 오른쪽 측면에 위치합니다. 퀵 버튼을 누르면 버튼에 할당된 기능이 실행되고 퀵 버튼을 길게 누르면 뜨는 ‘퀵 런처'라는 콘텍스트 메뉴가 뜹니다. 퀵 런처에서는 할당된 기능을 변경할 수도 있습니다. 또 빠르게 사용할 수 있
`퀵 버튼을 길게 누르면 뜨는 '퀵 런처'라는 콘텍스트 메뉴가 있습니다.` 혹은 `퀵 버튼을 길게 누르면 '퀵 런처'라는 콘텍스트 메뉴가 뜹니다.' 가 맞을 것 같습니다.

이건 다른 질문인데, '퀵 런처'를 '콘텍스트 메뉴'라고 볼 수 있을까요?

2018-08-08 08:53 UTC, freekering commented on _posts/2018-07-25-paper-pro-ui-design.md
> +PAPER PRO에서는 프론트라이트와 더불어 색 온도를 조절할 수 있습니다. 색 온도는 차가운 백색부터 황백색까지 화면의 색을 조절할 수 있는 기능입니다. 색 온도를 사용하면 특히 밤에 책을 읽을 때 도움이 됩니다. 황백색에 가까울수록 숙면을 방해하는 블루라이트가 줄어들기 때문입니다.
프론트라이트의 밝기의 색 온도를 조절하는 것이므로 `프론트라이트의 밝기와 더불어 색 온도를 조절할 수 있습니다.` 가 더 적확한 표현인 것 같습니다.

2018-08-08 08:53 UTC, freekering commented on _posts/2018-07-25-paper-pro-ui-design.md
> +## 색 온도 조절 제스처
여기 본문에 보면 `프론트라이트`와 `색 온도`가 마치 별개의 개념인 것 처럼 서술된 문장들이 있는데, 제 의견으로는 개념상 `프론트라이트`에 기존에 한손가락 제스처로 조절하던 `밝기`와 `색 온도` 두 개의 변수가 있다고 보는게 맞을 것 같습니다. (기존에는 밝기 밖에 없었지만)

그래서 손가락 개수에 따라 대응되는 개념이

1개-프론트라이트
2개-색 온도

가 아닌,

1개-프론트라이트의 밝기
2개-프론트라이트의 색 온도

가 맞지 않나 싶습니다.

2018-08-08 08:53 UTC, freekering commented on _posts/2018-07-25-paper-pro-ui-design.md
> +PAPER PRO가 출시된 이후로 꽤 많은 시간이 흘렀습니다. 앞으로도 사용자분들이 주시는 피드백을 반영하고 사용자 리서치를 통해서 더 개선해 나가야 합니다. 물론, PAPER, PAPER Lite도 지속해서 개선해 나갈 예정입니다. 갈 길이 멉니다.
물론 뒤에 `,` 가 있어서 `PAPER와 PAPER Lite도` 와 같이 `,` 가 아닌 다른 연결어나 부호를 쓰는게 좋을 것 같습니다.

2018-08-08 08:53 UTC, freekering commented on _posts/2018-07-25-paper-pro-ui-design.md
> +가로모드로 책을 읽으면 어떤 좋은 점이 있을까요? 한 화면에서 두 페이지를 볼 수 있어서 마치 종이책을 읽는 듯한 경험을 할 수 있습니다. 글로 이루어진 책을 볼 때 페이지 사이 여백에서 한 템포 쉬어갈 수도 있습니다. 가로모드가 특히 빛나는 순간은 만화를 볼 때입니다. 크게 두 페이지에 걸친 그림이 많은 [원펀맨](<https://ridibooks.co
이건 개인적인 의견인데, 원펀맨을 시원시원하게 볼 수 있다고 해도 참고할만한 이미지가 없으면 별로 와닿지는 않을 것 같은데.. 그보다는 실제 이미지로 보여줄 수 있는 작품(페이퍼 프로 소개 영상에 쓰인 열혈강호 화면이라던가..)으로 바꿔보는게 어떨까요? (물론 그 이미지를 여기서도 쓸수있다는 전제하에요.. 안되면 어쩔 수 없고..)

2018-08-08 09:53 UTC, jihyeleee commented on _posts/2018-07-25-paper-pro-ui-design.md
> +이전 모델과 다르게 PAPER PRO에는 전원 버튼, 페이지 넘김 버튼 외에 하나의 버튼이 더 있습니다. 버튼의 이름은 ‘퀵 버튼'으로 오른쪽 측면에 위치합니다. 퀵 버튼을 누르면 버튼에 할당된 기능이 실행되고 퀵 버튼을 길게 누르면 뜨는 ‘퀵 런처'라는 콘텍스트 메뉴가 뜹니다. 퀵 런처에서는 할당된 기능을 변경할 수도 있습니다. 또 빠르게 사용할 수 있
'특정 항목이나 컨텍스트 프레임에 영향을 미치는 작업'을 제공하는 메뉴가 콘텍스트 메뉴라고 정의되어 있어서 해당 용어를 사용했습니다. 다이얼로그의 성격과는 조금 다른 것 같고요. 아래 문서를 참고했습니다.
https://developer.android.com/guide/topics/ui/menus?hl=ko#context-menu

2018-08-08 09:54 UTC, jihyeleee commented on _posts/2018-07-25-paper-pro-ui-design.md
> +## 색 온도 조절 제스처
그러면 프론트라이트를 모두 밝기로 바꾸는 게 정확할 것 같은데요, 프론트라이트를 따로 언급해주지 않아도 될까요?

2018-08-08 09:55 UTC, jihyeleee commented on _posts/2018-07-25-paper-pro-ui-design.md
> +PAPER PRO가 출시된 이후로 꽤 많은 시간이 흘렀습니다. 앞으로도 사용자분들이 주시는 피드백을 반영하고 사용자 리서치를 통해서 더 개선해 나가야 합니다. 물론, PAPER, PAPER Lite도 지속해서 개선해 나갈 예정입니다. 갈 길이 멉니다.
'·' → 이 특수문자로 변경했습니다.

2018-08-08 09:57 UTC, jihyeleee commented on _posts/2018-07-25-paper-pro-ui-design.md
> +가로모드로 책을 읽으면 어떤 좋은 점이 있을까요? 한 화면에서 두 페이지를 볼 수 있어서 마치 종이책을 읽는 듯한 경험을 할 수 있습니다. 글로 이루어진 책을 볼 때 페이지 사이 여백에서 한 템포 쉬어갈 수도 있습니다. 가로모드가 특히 빛나는 순간은 만화를 볼 때입니다. 크게 두 페이지에 걸친 그림이 많은 [원펀맨](<https://ridibooks.co
왠지 이미지를 쓸 수 없을 것 같아서 첨부하지 않았습니다. 😭한 번 하늘님께 여쭤볼게요.

2018-08-08 10:07 UTC, jihyeleee commented on _posts/2018-07-25-paper-pro-ui-design.md
> +가로모드로 책을 읽으면 어떤 좋은 점이 있을까요? 한 화면에서 두 페이지를 볼 수 있어서 마치 종이책을 읽는 듯한 경험을 할 수 있습니다. 글로 이루어진 책을 볼 때 페이지 사이 여백에서 한 템포 쉬어갈 수도 있습니다. 가로모드가 특히 빛나는 순간은 만화를 볼 때입니다. 크게 두 페이지에 걸친 그림이 많은 [원펀맨](<https://ridibooks.co
하늘님께서 글 올린 후에 글 링크를 출판사에 드려서 이미지 사용 가능한지 여쭤보신다고 하시네요! 😅ㅋㅋ

2018-08-08 11:04 UTC, freekering commented on _posts/2018-07-25-paper-pro-ui-design.md
> +## 색 온도 조절 제스처
프론트라이트라는 단어는 위의 문단에서 한번 언급한 정도면 충분하지 않을까요?

2018-08-09 07:15 UTC, freekering commented on _posts/2018-07-25-paper-pro-ui-design.md
> +위와 같은 장점에도 불구하고 이전 모델인 6인치 PAPER·PAPER Lite에서는 지원을 고려하지 않았습니다. 6인치 기기 안에 두 페이지를 표시했을 때 너무 작아지기 때문입니다. PAPER PRO의 화면 크기가 커짐에 따라 가로모드를 지원할 수 있었습니다.
`6인치 기기 안에 두 페이지를` 보다는 `6인치 화면 안에 두 페이지를` 이 더 자연스러운 것 같습니다.

2018-08-10 01:17 UTC, freekering approved these changes

2018-08-10 06:34 UTC, namenu commented
@jihyeleee Conflict 해결해주시면 merge 하겠습니다!

2018-08-10 06:52 UTC, merged