Hyeonseok kim blog posting
ridi/ridicorp.github.io pull request #68
Opened 2018-08-08 01:27 UTC by HyeonseokKim

2018-09-07 03:08 UTC, namenu requested changes
구성은 개선이 되었는데, 서식을 많이 다듬을 필요가 있어 보입니다.
코멘트 드린 부분 수정해주시면 다시 살펴보겠습니다.

2018-09-07 03:08 UTC, namenu commented on _posts/2018-08-07-data-driven-planning.md
> +리디북스는 사내에 분석팀이 있지만 가급적 분석툴을 잘 활용하여 많은 시간을 아끼면서 의사결정하고 있습니다.
이 문장 자체와 다음 문단과의 연결이 조금 어색합니다.
`가급적`이라는 표현도 조금 구체화 해본다면 좋겠습니다.

2018-09-07 03:08 UTC, namenu commented on _posts/2018-08-07-data-driven-planning.md
> +# GTM 사용 예시 #1
내용 흐름이 GTM 예시로 급 선회하는 느낌입니다. 예시를 알아보겠다는 식의 연결이 필요할 것 같습니다.

2018-09-07 03:08 UTC, namenu commented on _posts/2018-08-07-data-driven-planning.md
> +![퀵메뉴](/blog/img/2018-08-07/fantasy_quick_menu.png){:data-action="zoom"}
아마 PC에서 폭을 맞추느라 일부러 이렇게 하신 듯 합니다만, 이미지에 좌우 여백이 많이 포함되어 스크린샷의 내용 확인이 어렵습니다.
너비는 마크다운에서 수동으로 지정해야 합니다.

2018-09-07 03:08 UTC, namenu commented on _posts/2018-08-07-data-driven-planning.md
> +# 측정하면 개선할 수 있습니다.
제목의 온점은 빼주세요

2018-09-07 03:08 UTC, namenu commented on _posts/2018-08-07-data-driven-planning.md
> +그렇다면 고객의 고충을 조금이라도 높은 확률로 해결하기 위해서는 어떻게 해야할까요? 먼저 아이디어는 가설일뿐 얼마든지 틀릴 수 있다는 전제하에 이를 최소한의 스펙으로 실험하고 검증해야 합니다. 이 때 검증을 위해 데이터를 얼마나 잘 활용하는지가 성공 확률을 높이는 방법이라고 생각합니다. 데이터는 사용자가 남긴 객관적인 흔적으로 고객의 실질적인 만족을 가늠
문장 끝에 공백을 두면 `<br>`로 처리가 되는데, 이는 블로그 글에 적합한 서식이 아닙니다.
문단은 `<p>`로 시작해서 `</p>`로 끝날 수 있도록 공백은 지워서, 문단들이 합쳐지거나 확실히 구분될 수 있게 해주세요.

2018-09-07 03:08 UTC, namenu commented on _posts/2018-08-07-data-driven-planning.md
> +category: planning
아직 planning 이라는 카테고리는 없습니다. design으로 해주셔도 될 듯 합니다.

2018-09-07 03:08 UTC, namenu commented on _posts/2018-08-07-data-driven-planning.md
> +리디북스는 다양한 채널로 유입되는 고객의 목소리를 취합합니다. 정리된 내용은 매일 TOC(Tears Of Customers, 고객의 눈물)라는 이름으로 전사 공유되고 각 팀에서 검토 후 우선순위에 반영합니다. 이외에도 FGI (Focus Group Interview), 일대일 UT (Usability Test)를 하며 고객의 고충을 이해하려 노력합니다.
괄호 앞의 공백은 제거해주세요.

2018-09-07 08:00 UTC, HyeonseokKim commented on _posts/2018-08-07-data-driven-planning.md
> +그렇다면 고객의 고충을 조금이라도 높은 확률로 해결하기 위해서는 어떻게 해야할까요? 먼저 아이디어는 가설일뿐 얼마든지 틀릴 수 있다는 전제하에 이를 최소한의 스펙으로 실험하고 검증해야 합니다. 이 때 검증을 위해 데이터를 얼마나 잘 활용하는지가 성공 확률을 높이는 방법이라고 생각합니다. 데이터는 사용자가 남긴 객관적인 흔적으로 고객의 실질적인 만족을 가늠
네.. 문장 뒤에 붙는 이상한 공백은 제거했습니다. 
그런데 이상하게 에디터에는 있는 줄바꿈이 실제는 적용되지 않는 부분이 있네요.. 이런 문장은 뒤에 <br>을 추가했습니다.. 다른 분들 포스팅 봐도 <br>을 붙인 경우가 간혹 있던데.. 원인을 모르겠네요.

2018-09-07 08:07 UTC, HyeonseokKim commented on _posts/2018-08-07-data-driven-planning.md
> +![퀵메뉴](/blog/img/2018-08-07/fantasy_quick_menu.png){:data-action="zoom"}
아.. 그렇군요. 이미지를 가운데에 맞추는 방법을 못 찾아서. 다른 분들 포스팅 보니 이미지 자체에 여백을 두었길래 똑같이 한건데.. 마크다운으로 여백값을 절대값으로 지정하려면 고정된 블로그 글 영역 최대 width 값에서 이미지 width를 봐서 지정해야한다는 의미같네요..

2018-09-11 03:37 UTC, namenu commented
바이너리 이미지가 불필요하게 많이 포함되어 rebase merge 하였습니다.

2018-09-11 03:37 UTC, closed without merging