블로그 포스트 추가: "Spark RDD 에서 GROUP BY 를 가장 빠르게 하려면?"
ridi/ridicorp.github.io pull request #71
Opened 2018-09-12 05:41 UTC by iamchanu

2018-09-12 05:43 UTC, iamchanu commented
`make serve` 했을 때 다음과 같은 에러가 발생해서 로컬에서 페이지로 확인해보지 못했습니다.
```bash
~/Workspace/ridicorp.github.io$ make serve
bundle exec jekyll serve
Configuration file: /Users/chanulee/Workspace/ridicorp.github.io/_config.yml
            Source: /Users/chanulee/Workspace/ridicorp.github.io
       Destination: /Users/chanulee/Workspace/ridicorp.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/style.scss':
                    Invalid US-ASCII character "\xE2" on line 5
jekyll 3.7.4 | Error:  Invalid US-ASCII character "\xE2" on line 5
make: *** [serve] Error 1
```

2018-09-12 06:58 UTC, namenu commented
@krazijames 님, 위와 같은 오류가 발생한다고 하는데 메세지에서 보이는 `style.scss` 파일의 정체를 아시나요?

2018-09-12 08:49 UTC, krazijames commented
@namenu 이상하네요.. 저장소엔 없는 파일인데.. 저도 당장은 정체를 모르겠습니다;

2018-09-14 02:00 UTC, iamchanu commented
@namenu 리뷰어를 더 추가해야 할 것 같은데 누가 좋을까요?

2018-09-20 10:15 UTC, namenu commented on _posts/2018-09-12-spark-rdd-groupby.md
> +[Apache Spark](https://spark.apache.org/docs/latest/) 는 대용량 데이터의 범용 계산을 위한 분산처리 시스템입니다. 기존의 Hadoop Map-Reduce 에 비해 훨씬 빠르면서도 간편하게 복잡한 데이터 연산을 처리할 수 있습니다. 전 세계적으로도 많은 사용자층을 가지고 있으며, 2018년 8월 현재 2.3.1 버
8월 현재 -> 추후 수정 필요

2018-09-20 10:15 UTC, namenu commented on _posts/2018-09-12-spark-rdd-groupby.md
> +Spark 를 사용하다 보면 데이터를 일정한 조건으로 그룹화하는 연산을 자주 사용하게 됩니다. 매출 내역을 날짜별로 묶어서 합계를 낸다거나 하는 경우죠. 이를 위해서는 Spark SQL 에서 `GROUP BY` 절을 이용하는 것이 가장 간편하지만, 가끔 복잡한 연산을 필요로 할 때는 RDD API를 사용하는 것이 더 나을 때가 있습니다. RDD API를
영어와 한국어 조사는 붙여 쓰는 것으로 알고 있습니다. (확인 필요)

2018-09-20 10:15 UTC, namenu commented on _posts/2018-09-12-spark-rdd-groupby.md
> +즉, 어차피 `Iterable[V]` 에다가 대고 무언가 종합(aggregation) 연산을 할거면, 처음부터 `groupByKey` 를 쓰지 말고 `reduceByKey` 나 `aggregateByKey` 를 쓰라는 것이지요. 이렇게 해야 하는 이유는, `groupByKey` 는 내부적으로 **map-side combine 을 하지 않도록 되어 있기 때
aggregate는 종합 보다는 집계로 많이 번역하는 것 같습니다.

2018-09-20 10:15 UTC, namenu commented on _posts/2018-09-12-spark-rdd-groupby.md
> +  .reduceByKey(_ + _)
앞에서 설명한 `aggregateByKey`를 사용할 수는 없을까요?

2018-09-20 10:15 UTC, namenu commented on _posts/2018-09-12-spark-rdd-groupby.md
> +그러나 생각해 봐야 할 것이 있습니다. `userIds: Iterable[Int] => userIds.toSet.size` 이 부분을 실행하는 시점에, 해당 날짜의 모든 구매내역의 개수와 동일한 수의 `userId` 가 메모리에 올라갑니다. 매출이 얼마나 성장하느냐에 따라 다르지만 이 숫자는 수백만에서 수천만까지 쉽게 올라갈 가능성이 있습니다. JVM 프
`구매내역의 개수` -> `트랜잭션의 건수`가 외부에서 이해하기 좋은 표현 같습니다.

2018-09-20 10:15 UTC, namenu commented on _posts/2018-09-12-spark-rdd-groupby.md
> +그러나 생각해 봐야 할 것이 있습니다. `userIds: Iterable[Int] => userIds.toSet.size` 이 부분을 실행하는 시점에, 해당 날짜의 모든 구매내역의 개수와 동일한 수의 `userId` 가 메모리에 올라갑니다. 매출이 얼마나 성장하느냐에 따라 다르지만 이 숫자는 수백만에서 수천만까지 쉽게 올라갈 가능성이 있습니다. JVM 프
~매출이 얼마나 성장하느냐에 따라 다르지만~

2018-09-20 10:15 UTC, namenu commented on _posts/2018-09-12-spark-rdd-groupby.md
> +  - 그룹의 최대 크기가 수십만 건 이상으로 큰 경우
그룹의 크기 관련해서 수만 건 / 수십만 건은 튜플의 크기에 따라 달라질 수 있는 부분이라 조금 애매한 표현 같습니다.

2018-09-20 10:15 UTC, namenu commented on _posts/2018-09-12-spark-rdd-groupby.md
> +두 개의 콜렉션을 이어서 하나로 만드는 **연결 (concatenation) 연산이 교환법칙과 결합법칙을 만족한다**는 점을 이용해 봅시다. 콜렉션 내에서 원소의 순서가 중요하지 않다면, 연결 연산을 어떤 순서로 적용하든간에 결과 콜렉션은 실질적으로 동일합니다. 이를 이용하면 다음과 같이 `groupByKey` 와 결과가 완전히 동일한 연산을 `reduc
`콜렉션 내에서 원소의 순서가 중요하지 않다면` 이라는 표현이 첫 번째 문장 안에 서술되어야 오해가 없을 것 같습니다.

2018-09-20 10:15 UTC, namenu commented on _posts/2018-09-12-spark-rdd-groupby.md
> +```
코드 예시 하단에 아래와 같이 `groupByKey`도 적어주면 어떨까요?

```scala
val groupedRDD: RDD[(String, Iterable[Int])] = keyValuePairRDD
  .groupByKey()
```

2018-09-20 10:15 UTC, namenu commented on _posts/2018-09-12-spark-rdd-groupby.md
> +우선, `Array` 는 불변(immutable) 콜렉션이라는 것에 주목해 봅시다. 불변 콜렉션끼리의 연결 연산은 우리가 얼핏 생각하는 것보다 훨씬 비효율적입니다. 길이 `m` 짜리 `Array` 와 길이 `n` 짜리 `Array` 를 연결한다고 하면, 원래의 두 객체는 그대로 두고 새로운 객체를 만들어서 원소들을 각각 복사해 줘야 합니다. 따라서 연결
이 문단은 조금 검증이 필요할 것 같습니다.

불변 Array더라도 아마 Hashed Array Mapped Trie로 구현되어 있을 가능성이 높습니다.

2018-09-20 10:21 UTC, namenu requested changes

2018-09-20 10:21 UTC, namenu commented on _posts/2018-09-12-spark-rdd-groupby.md
> +우선, `Array` 는 불변(immutable) 콜렉션이라는 것에 주목해 봅시다. 불변 콜렉션끼리의 연결 연산은 우리가 얼핏 생각하는 것보다 훨씬 비효율적입니다. 길이 `m` 짜리 `Array` 와 길이 `n` 짜리 `Array` 를 연결한다고 하면, 원래의 두 객체는 그대로 두고 새로운 객체를 만들어서 원소들을 각각 복사해 줘야 합니다. 따라서 연결
불변성을 나타낼 때 immutable과 persistent라는 두 표현이 있는데, 자료구조의 불변성을 나타낼 때에는 persistent를, 연산이나 조회에는 immutable을 사용하는 것으로 알고 있습니다.

2018-09-20 11:41 UTC, namenu commented
다른 리뷰어분들은 맥락 이해가 많이 어려울 것 같아서 제외하였습니다.
데이터팀 내부에서 강렬한 리뷰를 받아서 이미 완성도가 충분히 높다고 생각합니다.

2018-09-28 10:21 UTC, iamchanu commented on _posts/2018-09-12-spark-rdd-groupby.md
> +Spark 를 사용하다 보면 데이터를 일정한 조건으로 그룹화하는 연산을 자주 사용하게 됩니다. 매출 내역을 날짜별로 묶어서 합계를 낸다거나 하는 경우죠. 이를 위해서는 Spark SQL 에서 `GROUP BY` 절을 이용하는 것이 가장 간편하지만, 가끔 복잡한 연산을 필요로 할 때는 RDD API를 사용하는 것이 더 나을 때가 있습니다. RDD API를
네. 저도 그렇게 알고 있습니다만, 위키에 쓸 때 편의를 위해 띄어 쓰던게 그대로 남았네요.
수정하겠습니다.

2018-09-28 10:23 UTC, iamchanu commented on _posts/2018-09-12-spark-rdd-groupby.md
> +즉, 어차피 `Iterable[V]` 에다가 대고 무언가 종합(aggregation) 연산을 할거면, 처음부터 `groupByKey` 를 쓰지 말고 `reduceByKey` 나 `aggregateByKey` 를 쓰라는 것이지요. 이렇게 해야 하는 이유는, `groupByKey` 는 내부적으로 **map-side combine 을 하지 않도록 되어 있기 때
초안에는 글의 다른 부분에 "집계"라는 표현이 많이 쓰여서 "종합"이라는 번역을 선택했는데, 이제 없어졌네요.
"집계"로 바꾸겠습니다.

2018-09-28 10:23 UTC, iamchanu commented on _posts/2018-09-12-spark-rdd-groupby.md
> +  .reduceByKey(_ + _)
`reduceByKey` 와 내부적으로 동작은 거의 같고, `reduceByKey` 를 쓰는게 가독성이 더 깔끔합니다.

2018-09-28 10:24 UTC, iamchanu commented on _posts/2018-09-12-spark-rdd-groupby.md
> +  - 그룹의 최대 크기가 수십만 건 이상으로 큰 경우
단순히 크다/작다로 표현하면 너무 모호한 것 같아서 구체적인 숫자를 적었는데, 말씀하신 문제가 있긴 합니다.
좀더 고민해 보겠습니다.

2018-09-28 10:41 UTC, iamchanu commented on _posts/2018-09-12-spark-rdd-groupby.md
> +우선, `Array` 는 불변(immutable) 콜렉션이라는 것에 주목해 봅시다. 불변 콜렉션끼리의 연결 연산은 우리가 얼핏 생각하는 것보다 훨씬 비효율적입니다. 길이 `m` 짜리 `Array` 와 길이 `n` 짜리 `Array` 를 연결한다고 하면, 원래의 두 객체는 그대로 두고 새로운 객체를 만들어서 원소들을 각각 복사해 줘야 합니다. 따라서 연결
- 제가 잘못 적었네요. 엄밀히 말해 Array 는 불변은 아니고 가변 콜렉션입니다. 멤버 하나하나에 reassign 을 할 수 있으니까요.
다만 Array 에 `+=` 나 `++=` 연산이 적용될 때에는 마치 불변 콜렉션들처럼 양쪽 Array 의 원소를 일일이 복사하는 식으로 이루어집니다. 사실 이건 엄밀히 말해 불변/가변 여부보다는, `++=`  나 `+=` 연산을 따로 override 하느냐 안하느냐의 문제인 것 같네요... 좀더 조사해본 후 정리해 보겠습니다.
- 그리고 스칼라 Array 는 단순히 자바 배열의 또다른 표현입니다. HAMT 를 구현하지는 않는 듯 합니다.
- O(n*log n) 은 다음과 같은 계산에서 나왔습니다. `1*n + 2*n/2 + 4*n/4 + ... + n*1 = n * log(2)n`
- 스칼라에서 불변/가변 콜렉션을 포함하는 패키지 이름이 `scala.collection.immutable` 와 `scala.collection.mutable` 입니다.

2018-10-02 08:03 UTC, iamchanu commented
@namenu 님이 언급하신 내용 수정했습니다.
추가로 설명이 좀더 필요할 것 같은 부분에 각주를 넣었습니다.

2018-10-02 08:53 UTC, namenu approved these changes

2018-10-04 04:08 UTC, merged

2018-10-04 04:43 UTC, namenu commented
배포되었습니다.
https://www.ridicorp.com/blog/2018/10/04/spark-rdd-groupby/

추가 수정사항:
https://github.com/ridicorp/ridicorp.github.io/commit/2cc6a87c6e1813fe34f7059f6a9d8815ecb91feb